### ISSUE TITLE
Compatibility for rotating bodies

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#1106]
Pre-Cardano rotating bodies serialize an angular velocity instead of an angular frequency and α and δ of pole.

**Comment by eggrobin** [comment]
Still needs to be done in the interface and the C#.

**Comment by pleroy** [comment]
We cannot implement compatibility by rewriting a pre-Cardano file.  That would result in very complex code and it wouldn't be nice to the users: imagine a future where we release Dedekind but some people don't see any change because they are stuck in time in Cantor.

We have two cases:
* RealSolarSystem: the bodies already have a J2 and an axis properly set.  We need to get their rotational elements from the proto through `SolarSystem` and patch them.
* Something else (including stock KSP).  We need to somehow get from the C# side the rotational elements of each body (the axes are all vertical and there is not J2) and patch them.

This sounds non-trivial but then the only alternative is to break compatibility between Cantor and Cardano.  We need to make a decision on this issue before releasing Cardano.

**Comment by pleroy** [comment]
We decided that Cardano would not be compatible with Cantor.  The compatibility code was removed in #1241 (and at least one bug was fixed where rotating bodies would be deserialized as point masses).
