### ISSUE TITLE
Crash in map view

### ISSUE THREAD

**Issue by wagnerrp** [mockingbirdnest/Principia#1114]
Application crashes with Windows crash dialog immediately upon opening the map view on a vehicle in orbit, or shortly after exiting the atmosphere if already in map view.  Crash logs show the latter case, and crash occurs consistently 38 seconds after vehicle leaves the atmosphere and Principia takes over.

https://gist.github.com/wagnerrp/06b2ec8b9282650bb8ef55ec0c045dfc

**Comment by eggrobin** [comment]
The logs indicate that you are using a custom solar system (other than RealSolarSystem).
This is an "Apocalypse" crash. As explained in [the relevant section of the FAQ](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#kopernicus-users), this is due to the system being unstable, in this case after 3.9744×10⁶ seconds (46 days).  It so happens that it takes about 38 seconds to integrate the solar system to 46 days in the current state of your save.
You can see pictures showing such an instability in #631 (these pictures cannot readily be produced in the latest version of principia: the crash would occur before the bodies come close, and they were produced with the stock KSP system, which principia now patches to eliminate the instability).

How is your solar system customized? (I can't see what's in the system, because this particular set of logs starts with loading a save, rather than creating a new one).

**Comment by pleroy** [comment]
Conclusion as discussed on IRC:
```
<wagner> yes. it's on 6.4x
<egg|z|egg> wagner: well there's your problem
<egg|z|egg> wagner: see the last paragraph of this bit of the FAQ https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#kopernicus-users
<wagner> ah. i assumed (incorrectly) that the adjustments made to stock would apply in scaled up stock
<egg|z|egg> nah, they don't even apply if you just add stuff to stock, because we'd override kopernicus
<egg|z|egg> as soon as anythng kopernicus happens, the system must be made stable with kopernicus configs
<egg|z|egg> wagner: we provide a config for the unscaled system, I guess you could try scaling it to get a patch for the 6.4 system
<wagner> so basically i need to launch a new game, pop up a craft in orbit to engage principia, turn on high time warp, and just keep adjusting the initial properties until everything is stable?
<egg|z|egg> wagner: well, once you make a new save, the principia's body properties are fixed for that game
<egg|z|egg> wagner: so patch things, make a new game, and timewarp until it crashes (or doesn't :-p)
<egg|z|egg> wagner: no need for a ship
<egg|z|egg> wagner: you may want a timewarp mod, to timewarp fast
```
