### ISSUE TITLE
Current build of Master branch broken

### ISSUE THREAD

**Issue by zilti** [mockingbirdnest/Principia#1272]
I've built the current Master branch using VS2015. I'm on KSP 1.2.2. Solar system is scaled to 10x, I also used the Kopernicus config given in the Principia docs (and 10x-ed the semiaxes in there).

I've done this with a fresh savegame. When I launch a vessel that exits the atmosphere for the first time, the game's sound and to a lesser extent the graphics stutter and jump for a couple of seconds, then the vessel gets immediately placed into a ridiculously huge orbit and speed (over 60km/s, solar orbit with 667'801Mm Apoapsis). 

I then thought I'd fast-forward the game with max speed to see what happens. After 39 days I get this error:

```
Error extending trajectory for Tylo. Error trying to fit a smooth polynomial to the trajectory. The approximation error jumped from +2.60687141446609748e-03 m to +7.91836256750264292e+04 m at time +6.43680000000000000e+06 s. The last position is {+2.66108543749146362e+11 m, +5.97867922296658081e+11 m, +3.62178477295497656e+09 m} and the last velocity is {-1.08413476717372887e+04 m s^-1, +8.77661345000041183e+03 m s^-1, +4.63633753300558283e+02 m s^-1}. An apocalypse occurred and two celestials probably collided because your solar system is unstable.
```

**Comment by pleroy** [comment]
As discussed on IRC the problems when exiting the atmosphere seem to be an incompatibility with some other mod.  We don't test or debug these cases because there is no end to the combinatorial explosion of things that can go wrong.

The "apocalypse" error is telling you that your solar system is unstable.  The stock KSP is ridiculously unstable in the presence of correct N-body gravitational computations, and any simple adjustment to the stock KSP will probably exhibit similar instabilities.  It was a lot of work to patch it up in Principia to make it stable.  I guess you'd have to redo that work for your scaled-up system.

FWIW we are confident that this is *not* a bug in Principia because Principia is able to correctly simulate the real solar system for decades.

**Comment by zilti** [comment]
Ok, I've later on recompiled it, and am using RSS now. With RSS I get the same "bug" at the brink of the atmosphere: it stutters and jumps in and out of the atmosphere, gaining ridiculous amounts of speed and the vessel getting flung into a solar orbit.

I don't know if, maybe, it has to do if the border to space is crossed propelled or unpropelled? I'll test that. Meanwhile I noticed that the jumping in/out only happens once, with barely any effect on speed, when I cross the earth/space border in physics warp.

Funnily, this only happens with Sigma Dimensions and with RSS. When I don't rescale the stock system, it runs fine.

**Comment by zilti** [comment]
I've tested it with RSS *only* now, the problem still persists. It's not a matter of propelled or unpropelled. I made a quick video: https://streamable.com/87tf0

**Comment by eggrobin** [comment]
Replicated.
