### ISSUE TITLE
UI Breaking unknown error

### ISSUE THREAD

**Issue by halfiuuu** [mockingbirdnest/Principia#1319]
So, i was accelerating, and boom error, and principia window is not working on my save anymore, it's empty and toggled makes a gray 20 px margin on left side of the screen with a 15% offset from bottom.

Good luck
[orbit.zip](https://github.com/mockingbirdnest/Principia/files/910899/orbit.zip)

**Comment by pleroy** [comment]
Can you give us your save?

**Comment by halfiuuu** [comment]
yea.. i kind of deleted it :/

**Comment by pleroy** [comment]
From looking at the log, we have an Apocalypse.  I suspect that this is an occurrence of the bug fixed by #1311.  I am unsure why the UI gets garbled, but we will probably never know since "the dog ate my save".  Marking as fixed in Cartan.  Please re-open if you reproduce it and can attach your save.
