### ISSUE TITLE
When trying to land on the Mun, the vessel sinks below the ground and explodes

### ISSUE THREAD

**Issue by AlexanderKunze** [mockingbirdnest/Principia#1346]
Error in the title. See the attached screenshots for a demonstration. The speed does not matter - The vessel will go below the ground, approximately until the command pod touches the surface, then there will be an explosion and the game will show that the Kerbal piloting the vessel has been killed. Before this happens, as the vessel dives into the surface, there is a rumble and persistent shaking of the screen. The bug occurs no matter where I try to land. Removing Principia solves the problem and allows normal landing.

Attached file also includes any and all log files I could find, and are the same as in #1345: After producing this bug (note: without exploding the vessel, just diving into the ground far enough to take the screenshots), I went on EVA above the surface (note that the vessel was NOT sunk in the surface), which then crashed the game.
[Bugreport_principia_Munsink.zip](https://github.com/mockingbirdnest/Principia/files/949887/Bugreport_principia_Munsink.zip)

**Comment by Hugger** [comment]
I am having a very similar problem. The Mun surface seems to jitter when you get close, and the shadows appear and disappear. During the landing I was going about 5 m/s, but the debugger reported a crash velocity of 88. 

Doing an EVA near the surface also causes my game to crash.

**Comment by eggrobin** [comment]
Managed to replicate the issue with a timewarp mod (BetterTimeWarp), which sets the timewarp altitude limit to 0 m, causing us to lower the rotating frame threshold to 0 m, and doing the same to manageability threshold.
This seems consistent with the symptoms above (misreported crash velocity, because terrain is moving at the wrong speed, weirdly sinking in the terrain, etc.).
I will add a `WARNING` log if the timewarp altitude limit is found to be 0 m on an airless body, and set the rotation/manageability threshold to 10 km in that case.

@Hugger, @AlexanderKunze, are you using a timewarp mod?

**Comment by AlexanderKunze** [comment]
@eggrobin Hi there. Thanks for getting back to me. Yes, in fact I am. (BetterTimeWarp seems to be the culprit). In that case, should I disable BTW for now?
