### ISSUE TITLE
Accumulate gravitational interactions in DoublePrecision

### ISSUE THREAD

**Issue by eggrobin** [mockingbirdnest/Principia#1351]
Different behaviour due to non-associativity being amplified by the uncorrected stock system's terrible Ляпунов exponent is expected, but Aardvark being stabler than Kerbol which is stabler than Sun points to a systematic error due to cancellation.

**Comment by pleroy** [comment]
Tried this, and it doesn't help, the system remains sensitive to the order.

**Comment by pleroy** [comment]
It turns out that using compensated summation (`Increment` or `Decrement`) is not correct: these methods are only valid if the addend is smaller that the current value.  For accelerations we don't have any guarantees to that effect, and it's clear that reordering the body will affect the final result.  Experiments with _Mathematica_ show that reordering the bodies results in an error which is of 52 bits are the beginning (fine) but which occasionally jumps to 40 bits.  When these errors accumulate the trajectories of the planets end up being affected significantly (remember that the stock system is very unstable).

Using full double precision fixes the problem, but we probably don't want to pay the cost of 10 additions/subtractions instead of 1 in the inner loop of the force computation.  For a stable solar system these inaccuracies have no effect whatsoever.

**Comment by pleroy** [comment]
Code pushed to [pleroy/1351](https://github.com/pleroy/Principia/tree/1351).

**Comment by oscardssmith** [comment]
Would either pairwise summation, or Kahan summation help this?

**Comment by pleroy** [comment]
See the reference to "compensated summation" in the comment above, which is another name for "Kahan summation".  Kahan summation can yield large relative errors for ill-conditioned sums.  That's one of these cases.

**Comment by oscardssmith** [comment]
And pairwise isn't helping enough?

**Comment by pleroy** [comment]
Pairwise is less precise than Kahan and has the same conditioning properties.

The numerical analysis above was mostly done to check that the sensitivity to order doesn't hide a bug.  It doesn't.  Done.  The problem of accurately predicting the Kerbin system over long periods of time is spectacularly uninteresting as that system is extremely unstable (on a scale of months in the stock game).
