### ISSUE TITLE
Some stock bodies have peaks that are higher than the time warp limit

### ISSUE THREAD

**Issue by maccollo** [mockingbirdnest/Principia#1413]
For example, Minmus highest points are around 5-6 km, but the timewarp limit is 3 km, making landing at these locations impossible with Principia.
Similar locations exist on Mun, Ike and Gilly.

**Comment by Ururh** [comment]
I confirm. It's even worse in RSS, where the Moon's Lunar Seas have an altitude of 7,5 km with the default timewarp limit of 5 km. At least with RSS it can be "fixed" with Kopernicus configs.

**Comment by eggrobin** [comment]
This seems complicated; it seems that KSP puts the inverse rotation limit way higher than the atmosphere or the highest peaks, which means we don't want to use that as our manageability threshold (we would like to manage vessels in LKO etc.).
We have to set the inverse rotation limit to something lower, because we do not currently support managing the vessel when KSP's frame is rotating.
We cannot easily get the altitude of the highest peak programmatically, so we cannot set an accurate lower threshold; we rely on the timewarp limit, which is inaccurate (or the atmosphere, which is generally much better).
For the moment, there is nothing we can do that wouldn't be equivalent to making Kopernicus configs setting the timewarp limit appropriately for every solar system out there; this can be done as a workaround if you need to land on mountains in the short term.

Eventually, we could support managing the vessel even when KSP is using a rotating frame, and that issue would disappear; this would also allow managing the vessel as soon as it leaves the ground even in an atmosphere, allowing use of our trajectory plots during ascent.

**Comment by pleroy** [comment]
Also related to #848.
