### ISSUE TITLE
Exception when accepting a contract to rescue a Kerbal from the surface of a body 

### ISSUE THREAD

**Issue by pleroy** [mockingbirdnest/Principia#1466]
This spawns the Kerbal directly in EVA and results in:
```
F0711 22:08:12.940775 7488 interface.cpp:636] System.NullReferenceException: Object reference not set to an instance of an object
  at principia.ksp_plugin_adapter.PrincipiaPluginAdapter.UnmanageabilityReasons (.Vessel vessel) [0x00000] in <filename unknown>:0
  at principia.ksp_plugin_adapter.PrincipiaPluginAdapter+<AdvanceAndNudgeVesselsAfterPhysicsSimulation>d__93.MoveNext () [0x00000] in <filename unknown>:0
```
Thanks to @gbesacier for doing a build at the latest commit, reporting the problem, and suggesting a fix in #1459.

**Comment by eggrobin** [comment]
Note that this is not specific to contract-spawned Kerbals: any Kerbal in EVA out of physics range will cause this error (even if it is on the surface or otherwise unmanageable, since this occurs in the unmanageability test).
However, I think the suggested fix is doing the wrong thing, since we still want to manage Kerbals that are orbiting far away; I will make a pull request to address this.

**Comment by gbesacier** [comment]
I don't think it stop managing Kerbals in space, just those that don't have an evaController due to specific reasons (which I thought included just being spawn out of the physics range)

**Comment by eggrobin** [comment]
I think not being in the physics bubble (i.e. being an unloaded vessel) implies not having an `evaController` (and we definitely want Kerbals floating in space to keep being affected by gravity when we're not looking).

**Comment by eggrobin** [comment]
Yeah, I just checked: `(vessel.evaController == null || !vessel.evaController.Ready)` keeps orbiting Kerbals on unperturbed conics (and even displays those conics).
