### ISSUE TITLE
KSP 1.2.2 + RSS + RO + Principia = Impenetrable gravity wall at 70km altitude 

### ISSUE THREAD

**Issue by zenmetsu** [mockingbirdnest/Principia#1612]
With a fresh install of KSP 1.2.2, and RSS+RO installed from CKAN, I added Cesàro release from the binary and launched a game.  I found that launching a rocket caused it to explode when transitioning to space, right around the 70km altitude point.

In trying to debug, I removed Principia and the problem went away.  When looking at the debug log, the ships experience a 90+G load when they hit the 70km barrier.  When I looked at it more carefully, it is as if the gravity is amplified immensely and the ship is thrown back towards the surface at a ridiculous rate.

**Comment by aw1621107** [comment]
Wait, you have RSS installed but the atmo to space transition is at 70km?

**Comment by zenmetsu** [comment]
Well, it isn't necessarily transitioning to space, but there is definitely a boundary right at 70km. 

This was a fresh install from steam of KSP 1.2.2, so I went ahead and deleted everything and repeated the same steps, and this time Principia isn't causing the problem.  I'm not sure what got mixed up the first time around.  I guess I can close this issue, but I would like to hear idea of what might have happened in the off chance that I have a repeat run-in with this problem.

**Comment by lamont-granquist** [comment]
I'm skeptical anyone can guess what you did to your install.  70km doesn't map onto anything obvious for Earth or Kerbin.

A plausible guess might be that the RSS/Kopernicus config was messed up and applying the inverse rotation for Kerbin to Earth on one side or the other, and so the disagreement between Principia and the rest of the game at the inverse rotation threshold caused the massive shift in velocity and delta-v and a 90G acceleration.   But I think the inverse rotation threshold of Kerbin is going to be 85km not 70km (5km out of the atmo, just like the 145k inv threshold for Earth)?

Handling inverse rotation is new to Cesàro, but it also shouldn't affect planets with atmosphere, and with the 70km altitude seeming to not match anything, so maybe it is, maybe it isn't?

But it sounds like some combination of Principia/FAR/RSS/Kopernicus being deeply confused.

**Comment by eggrobin** [comment]
@lamont-granquist, you're off-by-one mathematician, Chasles (just released) handles inverse rotation; Cesàro did not.

@zenmetsu, my hypothesis is the following: from the fact that *something* happens at 70 km, we can conclude that the Kopernicus config was not applied as expected, and that Kerbin's atmosphere height of 70 km was still there; we can also assume that the rest of the Kopernicus config was missing, so that gravity was Kerbin's. However, RealSolarSystem was detected by ModuleManager, so that Principia applied Earth gravity as soon as you left the atmosphere; the sudden jump in gravity pulled your vessel back into the atmosphere, whence it emerged again, and with a few iterations of this your craft was accelerated in an absurd fashion.

**Comment by zenmetsu** [comment]
Fair enough.  @eggrobin I like your explanation, but I'd figure at most I'd see 1G of extra acceleration from Earth.  I have no clue where the 90G (it was actually 94G) came from.  I think something failed to apply via CKAN, and as stated I could not replicate the issue after burning everything down and reinstalling.  I'll chalk it up to CKAN failing to install some dependency.  

My apology for the firedrill.

**Comment by lamont-granquist** [comment]
Ah right, been too long since I played stock...
