### ISSUE TITLE
Crash during very high timewarp at space center

### ISSUE THREAD

**Issue by MikeOnTea** [mockingbirdnest/Principia#1703]
Having a probe on collision course with earth and then warp at 10 million speed (with betterTimeWarp) causes a crash. May be related to #1628. Does not crash at 100k warp for me.

Used mods with the save: RO/RP-0/RSS development versions for 1.3.1 plus their dependencies
procedural parts, b9 procedural wings, Realengines, RealChutes should hopefully be all needed part mods.

[savegame.zip](https://github.com/mockingbirdnest/Principia/files/1675453/savegame.zip)

[INFO.20180129-224231.zip](https://github.com/mockingbirdnest/Principia/files/1675434/INFO.20180129-224231.zip)

[JOURNAL.zip](https://github.com/mockingbirdnest/Principia/files/1675593/JOURNAL.zip)

part of ksp.log immediately before the crash:

> [WRN 23:03:56.156] [F: 289842]: Vessel R-1 Probe crashed through terrain on Earth.
[LOG 23:03:56.156] -INFO- Tac.LifeSupportController[FFEE6242][5900.98]: Vessel Destroyed [ebd6cc3e-0e35-424f-a400-03695badd3b4] R-1 Probe
[LOG 23:03:56.157] [Vessel R-1 Probe]: Vessel was destroyed.
[WRN 23:03:56.157] [F: 289842]: Vessel R-1 Debris crashed through terrain on Earth.

**Comment by pleroy** [comment]
Decoded stack trace:

[`numerics/fit_hermite_spline_body.hpp:85`](https://github.com/mockingbirdnest/Principia/blob/6039cbb001e31796edef56c11e407a75dcfeda10/numerics/fit_hermite_spline_body.hpp#L85)
[`physics/discrete_trajectory_body.hpp:179`](https://github.com/mockingbirdnest/Principia/blob/6039cbb001e31796edef56c11e407a75dcfeda10/physics/discrete_trajectory_body.hpp#L179)
[`ksp_plugin/vessel.cpp:431`](https://github.com/mockingbirdnest/Principia/blob/6039cbb001e31796edef56c11e407a75dcfeda10/ksp_plugin/vessel.cpp#L431)
[`ksp_plugin/vessel.cpp:191`](https://github.com/mockingbirdnest/Principia/blob/6039cbb001e31796edef56c11e407a75dcfeda10/ksp_plugin/vessel.cpp#L191)
[`ksp_plugin/plugin.cpp:756`](https://github.com/mockingbirdnest/Principia/blob/6039cbb001e31796edef56c11e407a75dcfeda10/ksp_plugin/plugin.cpp#L756)
[`base/thread_pool_body.hpp:80`](https://github.com/mockingbirdnest/Principia/blob/6039cbb001e31796edef56c11e407a75dcfeda10/base/thread_pool_body.hpp#L80)

**Comment by pleroy** [comment]
I think I have a theory.

We detect collisions in the force computations and bubble up a status to the integrator.  The integrator squirrels away that status and keeps integrating no matter what.  Once the desired time has been reached it returns the status.  This is important to preserve the invariant that desired time has been reached.  Anyway, so far so good because the trajectory of the pile-up is _not_ downsampled.

Then we advance the time of the vessel.  To do this we take the trajectory of the pile-up, which is probably quite chaotic, and use it to construct the trajectory of the vessel, which _is_ downsampled.  Things go downhill from there.

I am tempted to say: don't build a trajectory for a vessel that you are going to destroy anyway, but I am concerned that not calling `Vessel::AdvanceTime` in this case might break invariants...
