### ISSUE TITLE
CKAN Integration

### ISSUE THREAD

**Issue by MagixInTheAir** [mockingbirdnest/Principia#1720]
Is it on the roadmap ? It would help a lot, as the install procedure is non-trivial.
Thank you

**Comment by scimas** [comment]
Why is the install procedure non-trivial? It is as simple as extracting a zip and copying and merging the GameData folder; no dependencies to take care of either.

**Comment by njbrown09** [comment]
@scimas thats exactly what non-trivial means.......

**Comment by pleroy** [comment]
We have no plans to integrate with CKAN.  We prefer that people come to github or the forum threads where they can find documentation, information about how to report bugs, and general assistance from fellow players.

In particular, the bug reporting procedures are different from other mods, so if the users follow the standard procedure of giving us the `KSP.log` file, the bug report is useless.

Furthermore, Principia has system dependencies (like the C++ runtime) that CKAN cannot manage.

**Comment by bqv** [comment]
I hate to add noise to an issue, but given no response was given and the evident overwhelming support for @draeath's point, registering my loud agreement

**Comment by RaphaelDD885** [comment]
+1

**Comment by harveywalker500** [comment]
+1

**Comment by pwnorbitals** [comment]
I think the current status of this issue is misleading. It's marked as "complete", even though it's wontfix, and we probably should mark it as closed instead, or better yet, re-open it to discuss it a bit more and give it the attention it deserves. @pleroy, we all love Principia and want the best for it; CKAN is a great way to make it discoverable and bring new people to help with the project - and I'm sure we can find ways to work around the issues you raised. Would you be open to discussing those ?

**Comment by pwnorbitals** [comment]
@eggrobin letting you also know about this issue
