### ISSUE TITLE
Continue after apocalypse?

### ISSUE THREAD

**Issue by rongcuid** [mockingbirdnest/Principia#1756]
I do not know whether this is possible since I don't know the internals of Principia. However, I'd say it would be interesting to fly spaceships in complete chaos. For example, the popular mod Galileo's Planet Pack has an (insanely designed) 2:1 binary system, and Principia throws an apocalypse immediately. Since this mod uses N-body simulation anyways, shouldn't it be able to continue regardless of a stable orbit? I can be very wrong since I don't have training in numerical simulation.

Or, at least, allow continuing if only a minor part of the system falls apart. Perhaps combine bodies and their momentum, or delete them when going too far, etc.

**Comment by pleroy** [comment]
It's unfortunately not possible to continue after an apocalypse as many of the internal invariants of Principia are violated in this situation.

However, it is possible to configure Principia so that it handles property the solar systems that are unstable or otherwise funky.  This is done by dropping in the `GameData` directory a `.cfg` file specifying the parameters to use when integrating the solar system.  The [wiki ](https://github.com/mockingbirdnest/Principia/wiki/Principia-configuration-files) has a page that describes in details the syntax and meaning of the various configuration files.  In your case you'd need to configure the [`principia_numerics_blueprint`](https://github.com/mockingbirdnest/Principia/wiki/Principia-configuration-files#the-principia_numerics_blueprint-configuration).  I suggest to start with `BLANES_MOAN_2002_SRKN_14A` for the ephemeris integrator and with a time step of `30 min`.  This should have roughly the same behavior as the default used by Principia.  Then you should go through trial and error to reduce the time step until you reach a point where the apocalypse disappears (it will, ultimately).  For instance, go down to `15 min` and see if it helps.  If not, try `7 min`, etc.  Each time you cut the time step by a factor of 2, the computational cost will double, and the accuracy of the computation will increase by a factor of about 30 (because that integrator is of order 6 and 2<sup>6</sup>  = 32).  Note that a small time step will make Principia somewhat slower, although this should only be perceptible at high warps.

If you try this let us know how it goes, we are curious to hear if it helps.

**Comment by rongcuid** [comment]
I will try a smaller timestep with GPP. And I noticed that the cfg file's types looks suspiciously like Haskell's ADT. I wonder if you took inspiration from there? Or might it be something like F#?

**Comment by rongcuid** [comment]
To save time, I tested `BLANES_MOAN_2002_SRKN_14A` with `1 min` and no apocalypse message is shown. I am currently running the system at 100kx, and it seems that as of now, only Gauss's orbit is constantly changing, but it changes like in a resonance. The performance is OK at 100kx, but I don't know how well it goes if I add some vessels.

**Comment by rongcuid** [comment]
Still pretty stable after 55 years. I'd say it is good, thank you

**Comment by pleroy** [comment]
The description of the `.cfg` is just some kind of [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form) if that's what you're asking.

Glad to hear that a `1 min` step worked for you.  The performance should not change significantly when you add vessels.  If you add a mod that allows warping faster than 100 000× you might see a significant slowdown compared to the stock game.
