### ISSUE TITLE
JOURNAL files are filling disc space without limit

### ISSUE THREAD

**Issue by Kinexity** [mockingbirdnest/Principia#1809]
I have just found out that Principia created 429 GB of JOURNAL files on my computer - is this possible to add some kind of automatic file deleteing mechanism or something?

**Comment by eggrobin** [comment]
Turning on journaling in the logging settings has this effect, which is intended (the journal records everything that happens so that we can replay a session to debug complicated issues).

You should not turn on journaling unless you are replicating an issue for bug reporting (when journaling is off, no journal is produced). [It is off by default.](https://github.com/mockingbirdnest/Principia/blob/f7ce6a7c304c8ba7a47cd5261b0069feaf704201/ksp_plugin_adapter/ksp_plugin_adapter.cs#L129)

**Comment by eggrobin** [comment]
Note that in addition to gobbling up disk space, journaling will drastically slow down the game, so you really don't want to have it on unless you want a journal. :-)

**Comment by Kinexity** [comment]
I'm an idiot. Thanks :D
