### ISSUE TITLE
Lagrange point highlighting

### ISSUE THREAD

**Issue by dlathro1** [mockingbirdnest/Principia#1843]
Would it be possible to highlight Lagrange points in certain reference frames to asist with putting satellites in orbit around those points?
Thanks in advance.

**Comment by eggrobin** [comment]
This is tricky because the orbit of the Moon is (slightly, but noticeably) eccentric.
While, in the circular restricted 3-body problem (CR3BP), the Lagrange points do not move in the barycentric rotating frame, this is not the case in the more general elliptic restricted 3-body problem (ER3BP).

The correct reference frame for this more general case is the rotating-pulsating frame which fixes *both* bodies. The difficulty here is that the transformation to this frame involves a scaling, rather than just an orthogonal map; this is not something we support at the moment.

On the other hand, the fact that there is no appropriate reference frame for the Earth-Moon Lagrange point is definitely a nuisance, as not only is the Lagrange point not displayed in any frame, it moves around in all the frames we have. This less of a problem in the Kerbin-Mun system, which is close enough to the CR3BP for the Lagrange points to stay put in the barycentric frame; there the Lagrange points are not shown, but since they do not move it is possible to have an idea where they are.

**Comment by pleroy** [comment]
Closing as the rotating-pulsating frame introduced in [ابن الهيثم](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#%D8%A7%D8%A8%D9%86-%D8%A7%D9%84%D9%87%D9%8A%D8%AB%D9%85) addresses this issue properly.
