### ISSUE TITLE
Have a higher accuracy of setting maneuver nodes/adjustable accuracy

### ISSUE THREAD

**Issue by EthanWang706** [mockingbirdnest/Principia#1870]
This is a request, now, if I launch at the window that voyager 2 launched, in RSS, if possible, I can get into a orbit that fly by all 4 planets, but the accuracy of setting maneuver nodes makes it not really possible/takes a long time to adjust at maneuver time.

**Comment by pleroy** [comment]
As explained in the [Concepts](https://github.com/mockingbirdnest/Principia/wiki/Concepts#flight-planning) document this wouldn't be terribly helpful:

> The controls that let you plan your flight won't allow you to tune your Δv or your burn times extremely precisely (typically no finer than 1 mm/s). That's intentional: even if you were able to construct a flight plan that way, you wouldn't be able to execute it. If a small change of your Δv has a large effect on your future trajectory, you probably want to make smaller burns at different points along your mission.

So it's better to perform correction burns along the way: this is actually what happens in real life.  These correction burns can be planned as part of the flight plan.

There is another issue: even if the controls would let you specify the burns extremely precisely, and even if you were able to execute them flawlessly, the actual trajectory would diverge somewhat from the flight plan over long periods of time.  The reason is that the flight plan and the prediction are computed using a variable-step integrator, which sacrifices (some) accuracy for speed.  The actual trajectory on the other hand is computed using a fixed-step integrator, which focuses on accuracy.  How much the two diverge depend on how close you get to singularities, but again the best course of action is to do correction burns from time to time.
