### ISSUE TITLE
RSS has the weird inclinations.

### ISSUE THREAD

**Issue by njbrown09** [mockingbirdnest/Principia#1890]
I noticed that axial tilt works, but RSS still has the super weird inclinations even though axial tilt works,

**Comment by pleroy** [comment]
Sorry, but I have no idea what you mean by "RSS still has the super weird inclinations".  Could you be more precise, and provide steps to reproduce the problem, or a picture that demonstrates it?

Also, it's unclear from your description if the problem is a Principia problem or an RSS problem.

**Comment by njbrown09** [comment]
I made a modulemanager patch to remove the inclination. When i load the game with principia it breaks the patch. Here is the inclinations im talking about. https://gyazo.com/d2f51a4578928bec3155d1cc40990ffa

To reproduce just boot up the game with real solar system.

**Comment by eggrobin** [comment]
This is working as intended: for technical reasons tied to the limitations of KSP's terrain system, the current main body must always be vertical.
As a result, our axial tilt works by making the axis of the current main body vertical (while safely tilting the other celestials, since they do not have terrain until you come close to them).
This has the effect of tilting the universe.

The inclination that you observe in that picture is simply due to the horizontal being Earth's equator (note that this is a common reference frame for astrodynamical purposes anyway).

If you fly to another body, the universe will be tilted differently.

**Comment by njbrown09** [comment]
Right. The issue is that the modulemanager patch i wrote that removes the inclinations (It was bothering me) breaks when i run it with principia.

**Comment by eggrobin** [comment]
Yes, because Principia's axial tilt (in the gravity models) and its initial state override the Kopernicus elements.

**Comment by njbrown09** [comment]
Gotcha ok thanks!
