### ISSUE TITLE
Velocity addition when transiting from space to atmosphere with RSS.

### ISSUE THREAD

**Issue by sly31** [mockingbirdnest/Principia#1939]
I am having the same issue as previously mentioned in #1366 when transitioning from space to earth in 1.3.1 RSS with the Descartes release. I reverted back to the Dadekind release and reentry was normal.  Thanks.

**Comment by pleroy** [comment]
Can you give us steps to reproduce the problem?  Also, a save would be helpful.

**Comment by sly31** [comment]
I have included two screenshots to compare the velocity of the craft as it descends through the atmosphere from an initial 180km parking orbit.  Adjusting the periapsis to 70km should allow for a safe reentry, however, the craft is never affected by the atmosphere and keeps accelerating.  As mentioned above, reverting to the Dadekind release solves this problem I am having.  Thanks.
[Descartes test.zip](https://github.com/mockingbirdnest/Principia/files/2421638/Descartes.test.zip)

**Comment by eggrobin** [comment]
> the craft is never affected by the atmosphere and keeps accelerating

That's a different issue from #1366 then, which was a *sudden* increase of velocity exactly at the limit between space and atmosphere.

> Dadekind

Note that this is spelled [Dedekind](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#dedekind).

**Comment by eggrobin** [comment]
@sly31, which version of @ferram4's FAR are you using?

**Comment by sly31** [comment]
I am using version 15.8.1.

**Comment by eggrobin** [comment]
@sly31 
> I am using version 15.8.1.

That’s Lewis, which explains the behaviour that you describe in https://github.com/mockingbirdnest/Principia/issues/1939#issuecomment-424877759.

From @ferram4’s change log, emphasis mine:
> 0.15.9.1V "Liepmann"------------------------------------  
> Update for KSP 1.3.1 (though not strictly necessary)  
Update to MM 3.0.4 for KSP 1.3.1  
> Added ability to override structural stress values for aerodynamic failures on a per-part basis  
**Switch to applying forces through part.AddForce rather than rb.AddForce to allow Principia to handle gravity within atmospheres**
﻿Added functions to KSPAPI to check the status of any vessel's voxelization  
> […]

From our own change log, emphasis added:
> ### Δημόκριτος
> ####  User-facing features
> - Support for KSP 1.4.4 has been added: this version supports 1.3.1 and 1.4.x. Make sure you download the correct binary for your favourite version of KSP (the game will crash otherwise).
> - **Vessels are now managed by Principia when they are in the atmosphere.** This means that it's possible to see the history and prediction and to prepare flight plans immediately after launch. This works both with stock KSP and with Ferram Aerospace Research.
>
> […]

Principia Δημόκριτος and later (this includes Descartes) only work with FAR Liepmann and later; earlier versions of FAR do not make the aerodynamic forces visible to Principia, and since Principia controls the physics within the atmosphere, your vessel will plummet to its doom unhindered by aerodynamics.

Please update to FAR Liepmann. Note that FAR Lewis targets KSP 1.2.2, so you were using a version of FAR that targeted the wrong version of KSP.
