### ISSUE TITLE
Principia DLL failed to load

### ISSUE THREAD

**Issue by Sinderion29** [mockingbirdnest/Principia#2063]
I am getting the error 
"The Principia DLL failed to load.
The Principia DLL was not found at GameData\Principia\x64\principia.dll"
Upon loading/starting a game. The KSP folder is on my C disk, which seemed to be the issue on a similar post by nervvv some time back. The principia.dll file is definitely there. I am using ksp 1.4.5 with RSS installed, and downloaded the newest version of principia for 1.4.x and 1.5.1..

EDIT: To clarify, the "nervvv post" was #1626. I am also aware of post #2049 and the similar issue #1150  ,but as msnbcorp stated in 1150, it seems that normally "the error is launched but but the program is loaded anyway," while in our cases the program is not loading. Unlike in his case where there was an incompatibility with ksp 1.2.1, it states in the README that my version should be compatible with 1.4.X.. Moreover, my error appears differently (as copied above) as a text box in-game rather than the  System.BadImageFormatException: error in the log. I am new to this mod however, so I apologise if I am missing anything obvious here!

**Comment by pleroy** [comment]
Sorry for not getting back to you, it's really hard to debug what's going on on a user's machine.

One idea is that the `KSP_x64` exe must be run from the directory where it is located.  That's because the Principia DLL is looked up using a path relative to the current directory.  If for instance you have a shortcut that changes the directory where the exe runs, that would explain the problem.

Just a wild idea...
