### ISSUE TITLE
Instructions for building Principia from master

### ISSUE THREAD

**Issue by nikolain** [mockingbirdnest/Principia#2066]
I'm encountering some minor (but blocking) difficulties building from the sources. Specifically, Windows + Visual Studio 2017

The naive cloning of repo and opening Principia.sln results in errors like C:\Games\KSP\MODS\Principia\quantities\quantities.vcxproj : error  : The imported project "C:\Games\KSP\MODS\Google\protobuf\vsprojects\portability_macros.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Games\KSP\MODS\Principia\principia.props.

Does there happen to be some build instructions for building from sources and specifically for required dependencies?

**Comment by eggrobin** [comment]
For Windows, we have instructions in https://github.com/mockingbirdnest/Principia/blob/master/documentation/Setup.md.

**Comment by eggrobin** [comment]
Parts of these instructions are slightly out of date, e.g., "the git Powershell provided by GitHub for Windows" is no longer a thing, but the instructions should work in Powershell in general as long as git is in the PATH.

[posh-git](https://github.com/dahlbyk/posh-git) is a useful thing to have if you are going to be using git from Powershell a lot; the
```PowerShell
$GitPromptSettings.RepositoriesInWhichToDisableFileStatus += join-path  (gi -path .).FullName chromium
```
line is there to prevent it from wasting time trying to give you a status for chromium.

To be honest, we should just switch to using absl for the stack trace instead of having this really weird dependency on chromium, but we would have to make sure that our stacktrace decoder keeps working.
