### ISSUE TITLE
Parachutes ineffective below 8m above sea level

### ISSUE THREAD

**Issue by CaptainBalls** [mockingbirdnest/Principia#2072]
Hi this is with KSP 1.3.1, RSS 13.1.0 and  Principia εὐκλείδης. playing on windows 10 64-bit
When attempting to splash down with a probe or capsule on earth, the parachutes become ineffective (at about 8m sea level altitude) causing the vessel to impact the water at high speed.  

the time stamp in the linked "INFO" file is "08:20:08 . 332936" line 614
https://gist.github.com/CaptainBalls/c8474656a9365311ab5c32589a522a96
there is no "FATAL" file.

**Comment by eggrobin** [comment]
From IRC logs:
> <Mike`>  egg|laptop|egg, so apparently "chutes cut" isn't what happens, but physics stop working. Chutes stop working, engines stop working as well ("they kept firing but had no effect"). The guy retested and apparently the issue was gone when principia was removed.

**Comment by eggrobin** [comment]
Some questions to help us determine where we should look:
- does it happen with all kinds of parachutes, or just the FASA mercury ones that you were using here?
- does this happen deterministically?
- is this new in εὐκλείδης, or have you encountered it in previous versions of Principia?

**Comment by CaptainBalls** [comment]
Some questions to help us determine where we should look:

* does it happen with all kinds of parachutes, or just the FASA mercury ones that you were using here? _it happens with realchutes as well_
* does this happen deterministically? _all attempts to land in the ocean end with exlpoding parts_
* is this new in Εὐκλείδης, or have you encountered it in previous versions of Principia?_this is my first attempt to play with Principia_

**Comment by MikeOnTea** [comment]
I can reproduce the problem. Also happens with the previous release.
I suspect there aren't many reports because in my test the capsule survives the splashdown, at around 15 m/s, while it had a speed of 6 m/s while the chute was working.

**Comment by eggrobin** [comment]
8,4 m is indeed the difference between the mean radius that we use,
https://github.com/mockingbirdnest/Principia/blob/9e29425a9f7c836aab0c10ff9a583ad8bed40f20/astronomy/sol_gravity_model.proto.txt#L86-L93
and the one that RSS uses:
##### [KSP-RO/RealSolarSystem/GameData/RealSolarSystem/RSSKopernicus/Earth/Earth.cfg at 4c60999c, lines 30 to 34](https://github.com/KSP-RO/RealSolarSystem/blob/4c60999c40b0b26b47fb59db7214bfa203106510/GameData/RealSolarSystem/RSSKopernicus/Earth/Earth.cfg#L30-L34):
```C#
		Properties
		{
			displayName = Earth
			isHomeWorld = true
			radius = 6371000
```
Ours comes from the IAU WGCCRE 2009 report, which gives a value in km of 6371.0084 ± 0.0001, where the meaning of the uncertainty is unclear, since
> The uncertainties in the values for the radii and axes in Tables 4 and 5 are generally those of the authors, and, as such, frequently have different meanings.

The IAU WGCCRE 2015 report gives still gives 6371.0084 ± 0.0001, with the following note:
> (b) These values for the Earth are for comparison only. An IAU resolution (IAU 2015a) has adopted values for the equatorial and polar radii with less precision, giving values of
6378.1 and 6356.8 km, respectively.

However the IAU 2015 resolution A values are *nominal* values, and only include a value for the equatorial and polar radii, so that resolution is not very relevant if we want to keep using mean radii.
https://github.com/mockingbirdnest/Principia/blob/708a01eefe99fbe0bab39a82cb1891d7eacd54d0/quantities/astronomy.hpp#L25-L28 https://github.com/mockingbirdnest/Principia/blob/708a01eefe99fbe0bab39a82cb1891d7eacd54d0/quantities/astronomy.hpp#L39-L44

> If the value principia uses is more accurate here we might want to change the RSS value.

Possibly, but we should also try to figure out what is going on here, this is certainly unexpected.

There are some places in Principia that assume that being under the mean radius implies collision, which is broken in principle (although since KSP models bodies as spheres rather than ellipsoids it is not very visible); we should revisit that.

On the other hand, we would expect a collision detection from Principia to result in
1. the vessel blowing up;
2. a log message at the WARNING severity;

neither of which is happening. 8 m of free fall with ineffective parachutes is definitely not expected.

**Comment by zilti** [comment]
I have the distinct memory of having had that problem about two years ago, though not sure if with or without Principia.

**Comment by pleroy** [comment]
I was looking at this code recently for unrelated reasons and noticed that we were not adding the [intrinsic accelerations after a collision was detected](https://github.com/mockingbirdnest/Principia/blob/master/physics/ephemeris_body.hpp#L411).  I believe that this explains the bug.

Subsequent questions:
1. Should we use `mean_radius` or `0.9 * mean_radius` or something for the collision detection?  The pole on Earth is like 15 km below the mean radius.
1. The change in #2064 should cause us to destroy the vessel when it collides with a celestial.  Why is this not happening here?  Should it?  Do we have a lagging vessel?

**Comment by eggrobin** [comment]
Note: this issue was introduced by https://github.com/mockingbirdnest/Principia/commit/baa6eb9e3cb0105d820f78d1590600aea7150936#diff-360562aedddbc765add7381b8a92a3f8R415, in #2020, released in Erdős. @zilti’s two-year old issue is likely separate.
