### ISSUE TITLE
"Apocalypse has occurred" message never goes away

### ISSUE THREAD

**Issue by RocketSquid** [mockingbirdnest/Principia#2118]
I used the Extrasolar planet pack, which contains the moon Maol, which has an unstable orbit. The message saying an apocalypse has occurred is now permanent. I have done everything up to and including deleting the entire Extrasolar mod, to no avail. Making matters worse, the window is not hidden when the rest of the GUI is, and cannot be dismissed.

**Comment by eggrobin** [comment]
This is intentional.
The apocalypse is unrecoverable: it means that the solar system is broken, and cannot be used with Principia (at least not with the default settings for numerical integration).
The apocalypse is an internal consistency check (specifically, it checks that the trajectory of the planets can be interpolated). If that check fails, Principia no longer functions properly.
After the apocalypse, the solar system will behave in unphysical ways; planets may end up jumping around, especially with multistep integrators; the game is no longer playable, and the dialog is there to remind you of that fact.

The only reason why the apocalypse is not a hard crash anymore (it used to be) is to make it easier for users to know that the error is an apocalypse (and that they should therefore contact the solar system designer, not us) and to make it easier for the solar system designer to see what happens at the time of the apocalypse.

**Comment by eggrobin** [comment]
> deleting the entire Extrasolar mod

Note that changing the set of planets on a Principia save is not supported. Adding planets will cause a hard crash; it may be that removing them does not (if it does not, we probably should add such a consistency check), but Principia still knows about them, and will continue to simulate them and their influence.

**Comment by RocketSquid** [comment]
Is there any way to get rid of this, short of deleting principia or the
save?

**Comment by pleroy** [comment]
No.  As explained above, the solar system is just unusable with Principia: we do not know how to integrate it.  In other words, the Extrasolar mod is incompatible with Principia (as are most mods that add planets without bothering with stability).

I suppose that you could maybe patch Extrasolar to remove Maol and try to start a new game, but that seems clunky and there is no guarantee that it will work.

**Comment by RocketSquid** [comment]
Why hasn't it caused any problems yet? The only indication that anything
occurred is the message, and the fact that Maol's orbit looked wrong on the
map. There have been no disturbances to any bodies other than Maol, stock
or modded; nor to any craft.
