### ISSUE TITLE
manoeuvre node auto move while warping

### ISSUE THREAD

**Issue by LuctenFinger** [mockingbirdnest/Principia#2154]
as the title

**Comment by pleroy** [comment]
The title is rather cryptic, but I am assuming that you are talking about the manoeuvre node shown on the navball.  If so, it is working as it should: the direction of the manoeuvre is defined based on the Frenet trihedron at the time of the burn, and that's not fixed with respect to your vessel as you advance along your trajectory (your trajectory is typically not a straight line).

If you mean something else you'll have to provide details.

**Comment by MiracleMagician** [comment]
I guess what he means is this... The UT of manoeuvre keeps increasing
https://www.youtube.com/watch?v=RKPf_BKI6LQ

**Comment by eggrobin** [comment]
@MiracleMagician  
> The UT of manoeuvre keeps increasing

Oh, this is bad.

This is happening because, since Fáry, we take the start of the flight plan as a time base for the manoeuvres, but that keeps increasing if the past flight plan gets cut off by forgetting the history.

For now, as a workaround, set the history length to something long; the issue will only occur if the history gets cut off after the beginning of the flight plan.
