### ISSUE TITLE
Crash as fuel ends

### ISSUE THREAD

**Issue by MorePortal** [mockingbirdnest/Principia#2181]
Right before fuel ends in the current stage, game closes itself. I don't know which mod causes this error. I thought about KSP-IE (last installed), but it isn't the one that causes this issue.

https://gist.github.com/MorePortal/681e9ed19f7d1dd07b3a0ac5c1a27631

**Comment by pleroy** [comment]
The error message is trying to tell you that the part Rockomax64.BW (a fuel tank) has a mass of 0.  In stock, that part has a mass between 4 t (dry) and 36 t (full).  We don't know how to do physics with parts of mass 0 because, well, they don't exist in real life.  Obviously one of your mods is messing up with the part in non-physical ways.

**Comment by MorePortal** [comment]
Tank has zero mass even without Principia
