### ISSUE TITLE
The no name node glitch still persists

### ISSUE THREAD

**Issue by MiracleMagician** [mockingbirdnest/Principia#2196]
When loading a save or switching to another vessel in game, map screen seems to become laggier.
I can get stable 60 fps when prediction step set at 1024 with 1m tolerance, even with a 100 day flight planning, if I did't load a save during flight or switch vessel. After loading a save/ switch a vessel, framerate drops to about 40 when in map, and I can only get 50-55 fps in flight screen.

~~I can't figure out whether this is a principia problem or caused by some stock game glitch, since stock game aren't that performance intensive in map mode.~~ Maybe it's likely caused by principia, since I get ~125FPS without Vsync constantly in map when principia is not installed. 

I don't know whether this glitch is introduced in what principia version either, since I didn't played so much with pervious releases. If that brings up some inconveniences, I'm very sorry for that.

Game version 1.7.0, Principia version Fatou (After fixing #2188 )

**Comment by MiracleMagician** [comment]
Hmmm... Seems it's not happening every time I save/ load, but switching vessels seems to have a 100% happening rate.

**Comment by MiracleMagician** [comment]
And the no name node glitch still persists, but less often and only happens with the next upcoming node.
![screenshot39](https://user-images.githubusercontent.com/50024118/59147027-8408b980-8a28-11e9-89f2-2d30f84f4418.png)

**Comment by pleroy** [comment]
Is this related to the number of nodes that are displayed on the prediction/flight plan?  In other words, do you have a "slow vessel" and a "fast vessel", and does the slow vessel have many more nodes displayed (because of the shape of its trajectory) than the fast one?  When I try that, I seem to get <50 fps for one vessel and a solid 60 fps for the other.

Another question: when looking at the trajectories in the Tracking Station, do you see the same slowdown or do you see 60 fps for both?

It's not altogether clear what is happening.  KSP is horrendously bad at displaying nodes so we have to do a lot of work to try to speed things up.  Pinging @eggrobin who is travelling this week,

**Comment by MiracleMagician** [comment]
Oh, for switching vessels, I meant switching to another vessel and back.
![screenshot36](https://user-images.githubusercontent.com/50024118/59153461-a7655000-8a8c-11e9-80aa-212c8f0287cb.png)
![screenshot38](https://user-images.githubusercontent.com/50024118/59153462-a8967d00-8a8c-11e9-8c93-ebf80683f579.png)
I used Principia's target switching button, and after switching I cleared the target vessel, so the things 
rendered by principia should be the same.

When I'm in a low orbit around a small body or something that makes principia displays many nodes at once I indeed noticed some slowdown, but this is likely not the case I think.

**Comment by pleroy** [comment]
It might help if you could give us a journal of what Principia is doing.  The procedure is as follows:
1. In the main Principia window, in `Logging Settings` select `Record journal (starts on load)`.
1. Force a scene change (e.g., go to the Space Center and back to map view), check that the main window says `Journalling is ON` at the bottom right.
1. Play for 30 s or so, switch vessels exactly once, play for another 30 s or so (so that we can figure out what to look for in the journal).  Note that in this mode things will be quite slow because everything you do is logged to the journal.
1. Unselect `Record journal (starts on load)`.  It immediately takes effect.
1. In the `glog\Principia` directory you should have a file named `JOURNAL...`.  Share it with us, either as a gist or using whatever works for you (if it helps we have a 微信 account named `mockingbirdnest`).

**Comment by MiracleMagician** [comment]
Ok I found out what's really lagging my game. It's Sigma Dimensions. Sorry for false information... A second time...

**Comment by pleroy** [comment]
Well, it seems that the name node glitch is still there, so that's still a bug :-)
