### ISSUE TITLE
The tolerance and steps settings are not preserved across scene changes

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#2239]
The tolerance and steps settings on the main Principia window reset to the default values (1.0e-2 m and 1.02e3) on every scene change.

**Comment by pleroy** [comment]
Actually this is not a bug but it is confusing.

The tolerance and steps are saved by vessel: it makes sense because different parameters may be appropriate for different vessels.  So when a vessel is selected, the parameters for that vessel are displayed, and to the best of my understanding they are properly saved/restored on scene changes.  However, when no vessel is selected, the values displayed are the default.

It seems to me that the prediction settings should only be displayed when there is a vessel selected, pretty much like the flight plan.  This is going to require some rework of that part of the UI, though.

**Comment by scimas** [comment]
> The tolerance and steps are saved by vessel: it makes sense because different parameters may be appropriate for different vessels. So when a vessel is selected, the parameters for that vessel are displayed, and to the best of my understanding they are properly saved/restored on scene changes.

Yes, that is what I was expecting. But as of Fermat, the settings are not being saved per vessel. If you launch a rocket, make changes to said settings, return to KSC and go back to the rocket, the values are reverted to the default ones. I am able to reproduce this reliably with KSP 1.7.2 fresh install, both expansions and only Principia Fermat. The same thing happens with 1.6.1 and Fary.

In addition to this, the Principia main menu gets stretched to almost the full screen width due to the new version release message. I will open another issue for it. Apologise for the late reply, I haven't been able to play often in the recent days.

**Comment by scimas** [comment]
I've discovered another bug (maybe more than 1) that is related to this. Should I post the details here or raise another issue?

**Comment by eggrobin** [comment]
@scimas opening a new issue sounds good.

By the way, so as to clarify the exact behaviour that was fixed, the specific issue that you describe in your previous comment, 

> If you launch a rocket, make changes to said settings, return to KSC and go back to the rocket, the values are reverted to the default ones

and that was fixed by #2254 specifically happened if you changed the settings *without then going to map view*, i.e., without seeing the effect of the settings (since the prediction is only shown in map view); these changes would only take effect in map view.

Following #2254, the setting change will be persisted even if you do not look at the prediction before the next scene change.

**Comment by scimas** [comment]
The same issue happens on EVA. 
1. Change tolerance and steps settings
2. (optional) Go to, and come back from, map view
3. EVA a kerbal, which is I guess considered a new vessel, so the settings are restored to default ones
4. (optional) Change the tolerance and steps settings
5. (optional) Go to, and come back from, map view
6. Board the rocket

The settings have been reverted to default ones for the rocket too. I guess there are just too many edge cases for how this is handled.
