### ISSUE TITLE
Game crashes very frequently with the newest version of Principia

### ISSUE THREAD

**Issue by EthanWang706** [mockingbirdnest/Principia#2242]
This issue is reported by Reach
Note that this crash actually has a crash report, which is not common
There are no specific situations that caused the game to crash
The crash report and log is in the Discord server, as GitHub does not support rar files
@eggrobin

**Comment by eggrobin** [comment]
Crash dump and logs from discord:
[Crash_2019-07-09_202034.zip](https://github.com/mockingbirdnest/Principia/files/3383809/Crash_2019-07-09_202034.zip)
[glog.zip](https://github.com/mockingbirdnest/Principia/files/3383811/glog.zip)

```
KSP_x64.exe caused an Access Violation (0xc0000005)
  in module KSP_x64.exe at 0033:acdac704.

[...]

Read from location 00015ffc caused an access violation.
```

Note that the error does not seem to be in `principia.dll`, so we might somehow be causing Unity or the mono runtime to break; this has happened in the past, but it's annoying to debug.

**Comment by pleroy** [comment]
There are several confusing things with this crash:
1. The date in `error.log` is 2019-07-09_202422 (I am going to assume it's local time).  The date of the `crash.dmp` file is the same.  However the INFO logs are posterior to this (the earliest one has a name that says 20190709-203745) and they seem to finish with a normal shutdown of the game, so they don't help figuring out what was happening at the time of the crash.
1. There is no `KSP.log` file.  Do I get it right that this file is not present after the crash?  This is odd because it's created when the game starts and appended to.
1. The `crash.dmp` doesn't have any of our DLLs mapped.  I looked at some old `crash.dmp` that I have and they all have at least `principia.dll` mapped.  Of course it's conceivable that we are corrupting the memory so badly that the `crash.dmp` is not useful but somehow my gut feeling is that we would have gotten more complaints.

So I am rather lost at this point.  Any additional information that you could provide (more log files, what was happening at the time of the crash, etc.) would be very helpful.

**Comment by pleroy** [comment]
For the record, this has happened to me with 1.6.1 at the point of a scene change: 
[Crash_2019-07-28_114034.zip](https://github.com/mockingbirdnest/Principia/files/3448569/Crash_2019-07-28_114034.zip).

The crash appears to be in the same code section as in Crash_2019-07-09_202034.zip and generally looks very similar.  Interestingly, it's not happening on the UI thread, but on some auxiliary thread, and there is only KSP code on the stack.  One thinks of asynchronous finalization, but it's hard to make sense of the minidump.

**Comment by pleroy** [comment]
This problem seems to have vanished.  Closing.
