### ISSUE TITLE
Vehicle unstability if equipped with robotics parts

### ISSUE THREAD

**Issue by jlNiap** [mockingbirdnest/Principia#2248]
When robotic parts like hydraulic cylinder or servo is used in spacecraft, it become unstable. 
Stock items only used (KSP 1.7.2 and breaking ground 1.1.0).
Behaviour: craft start to spin and speed up to desintegration.
Some troubleshooting: 
- same craft without Principia -> No issue (to make sure)
- unstability is reduced with power applied and aerodynamic force (becoming more unstable while in space)
- unstability can be handle with big reaction wheels. (e.g. Servo F-12 needs 3 to 4 Large advance reaction wheels on a 8t spacecraft (after complete burn))

**Comment by jlNiap** [comment]
Additionial questions:
- would it be possible to have the option in the next version to keep the stock or the mod physics for the behaviour of the vessel?
- For this version, what is the code part that affect this part of the physics?

**Comment by pleroy** [comment]
> Behaviour: craft start to spin and speed up to desintegration.

I would imagine that robotic parts break some of the invariants that we depend upon, for instance by applying forces in an inconsistent manner so that they result in nonphysical torques.  To be honest, I don't see that fixing this is going to be a priority, if only because dealing with the vagaries of KSP is difficult and brittle.

> would it be possible to have the option in the next version to keep the stock or the mod physics for the behaviour of the vessel?

Nope.  This doesn't even make sense: for instance, vessels split and merge all the time, how is this going to work if they obey different rules?

> For this version, what is the code part that affect this part of the physics?

Mostly `ksp_plugin_adapter.cs`, `part.cpp`, `pile_up.cpp` `plugin.cpp` and `vessel.cpp`.  But really it's not that relevant.  The more interesting question is, what the heck is KSP doing with these robotic parts that causes spurious forces to appear?

**Comment by scimas** [comment]
Can confirm this happens with Principia and robotic parts. Game is basically unplayable with those parts unless you want to use ridiculous amounts of reaction wheels.

**Comment by zajc3w** [comment]
Everything is working perfectly fine.
testbed:
clean 1.8.1 KSP install including DLCs
Pricipia  Frobenius

Ship in LKO with all types of robotic parts in 2x symmetry, no reaction wheels enabled
robotic parts move without any unexpected effects, 

Ship in LKO with robotic parts without symmetry, no reaction wheels enabled
robotic parts move without any unexpected effects.

Ship in LKO with fuel tanks on pistons attached radially, slowly rotating, no reaction wheels enabled
Pistons extends and rotation slows down, just as expected.

Strongly suspect other  mod interaction rather than Principia/robotics bug.

**Comment by pleroy** [comment]
Thanks for the update.

**Comment by eggrobin** [comment]
I wonder whether Frobenius may have fixed that as a side effect of the preservation of angular momentum, since the symptoms involved spin.

**Comment by jlNiap** [comment]
Same as written above, now in 1.8.1 with Frobenius, no problem anymore (tested with exact same vessel and test vessels saved before). 
(and I just saw that Fubini is coming, I will try it when released).
So I think the problem is closed.

Thank you again for this mod

**Comment by jlNiap** [comment]
It seems to work fine with Fuchs too (and 1.9.1)
