### ISSUE TITLE
Is there a recommend CPU clock speed?

### ISSUE THREAD

**Issue by CoderChang65535** [mockingbirdnest/Principia#2255]
I am using a server running Win10 to play KSP with RSS, RO and Principia.
That means I have a not high CPU clock speed and it has a little frame loss so could you give me a recommend CPU clock speed to avoid it? I can disable some cores and close hyper-threading to raise it.
Btw, as I know, KSP only supports two cores most, so does Principia also follow that?

**Comment by pleroy** [comment]
It's quite hard to give recommendations because we are not testing this on a wide variety of processors.  In general, "a little frame loss" with RSS+RO+Principia is not unexpected.

For what it's worth, we are using ourselves fairly old processors (Sandy Bridge) in the 2.7-3.0 GHz range.

KSP only uses one core as far as I know.  Principia, however, tries to use all your cores for integrating different vessels and for asynchronous operations, so the more cores the better.  You'll gain a lot of performance that way, so you should pick more cores even if that means a slightly lower frequency.

**Comment by CoderChang65535** [comment]
> It's quite hard to give recommendations because we are not testing this on a wide variety of processors. In general, "a little frame loss" with RSS+RO+Principia is not unexpected.
> 
> For what it's worth, we are using ourselves fairly old processors (Sandy Bridge) in the 2.7-3.0 GHz range.
> 
> KSP only uses one core as far as I know. Principia, however, tries to use all your cores for integrating different vessels and for asynchronous operations, so the more cores the better. You'll gain a lot of performance that way, so you should pick more cores even if that means a slightly lower frequency.

We are using quite similar CPU. I am using E5-2570*2 so I have 32 cores and at most 3.0 GHz and the GPU is powerful enough. We should have nearly performance theoretically.
Maybe there are other mods or too many parts in my ship causing it so I will check it by myself.
Thanks for your reply and I will close this issue.
