### ISSUE TITLE
Vessels "forget" prediction settings upon landing

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#2443]
The trajectory prediction settings (tolerance and steps) are reset to default values as soon as a vessel touches the ground on any body. It would be preferable to not lose them. It gets slightly annoying when biome hopping.

I guess this will go along with #957.

**Comment by pleroy** [comment]
I don't think it's related to #957: the part of that issue that has to do with the prediction has been done long ago, the part that has to do with the plotting frame was not done because it's not clear if it's a good idea.

In the situation that you describe, Principia stops managing the vessel as soon as it hits the ground and destroys the internal `Vessel` object.  Thus the prediction, history, flight plan, parameters are all lost.  Keeping the vessel around while it is managed by KSP would be quite hard: Principia has no control over what happens in that case, e.g., if the vessel starts moving on wheels or something.  So we would need to peek at what KSP is doing and update the state of the vessel so that everything is consistent when we get back to managing it.  This may be possible, but it would be a good chunk of tedious work.

**Comment by scimas** [comment]
Agreed that you shouldn't need to keep track of everything that happens to a vessel when Principia isn't even managing it. All I want is for those two settings to be persistent, all the other things not being available is not really a big deal. (Although the possibility of a flight plan right from launch to landing is so tempting :smile: )

Do vessels have some kind of unique ID? That way you only need to keep track of those two settings (and not the full state) as long as the vessel exists. When you start managing the vessel, if you get the same ID for the vessel, restore those settings.

Although I can see that you would need to keep track of every vessel being created and destroyed even if Principia never gets to managing them.

**Comment by pleroy** [comment]
Fixed in #2455.
