### ISSUE TITLE
i have planet texture issue with your mod.

### ISSUE THREAD

**Issue by Vannadin** [mockingbirdnest/Principia#2447]
i have no idea why this happened, but when i use principia, i always have normal map texture issue.
![screenshot68](https://user-images.githubusercontent.com/23308367/72401428-4ffc3080-378f-11ea-9092-31bae8e8f1fe.png)
this one is moon with principia and

![screenshot89](https://user-images.githubusercontent.com/23308367/72401448-5e4a4c80-378f-11ea-8da4-ef06668a47f4.png)
this one is moon without principia. can you notice difference between two rims?

**Comment by pleroy** [comment]
Sorry, I have no idea what you are talking about.  Other than the fact that the two pictures show the Moon in different orientations and lightning (which makes the comparison hard) I don't see anything odd regarding the normal map or the rims.

You'll have to be more explicit about what you think is wrong.

**Comment by Vannadin** [comment]
sorry about lacked explanation. look at the rim, with principia, all normal map details are gone, except polar area. this happens only at moon and mercury for now. 
![screenshot94](https://user-images.githubusercontent.com/23308367/72492268-ea2ba980-385f-11ea-973c-ec8cad89a798.png)
this is same angle image with principia. lower left shadow details are all gone. i tried both single channel and two channel normal map but all not worked. 
p.s. i confirmed it's not related to scatterer

**Comment by pleroy** [comment]
From your github username I presume that you are using [VaNnadin's 16K RSS texture pack](https://spacedock.info/mod/1357/VaNnadin%27s%2016K%20RSS%20texture%20pack).

I believe that the problem is not specific to Principia, although Principia may make it more visible.  I believe that the problem comes from some glitch in the normal maps.  All the pictures below are *without* Principia.

The following is a polar view of the Moon on 1951-01-01 (the origin of RSS time) with your texture pack.   The lunar terminator looks good, but if you look at it carefully, you'll notice that the craters are lit from the *right* whereas the Sun is at the *bottom* of the picture.  This is a bit fishy:

![screenshot42](https://user-images.githubusercontent.com/7423020/72689253-e02fd200-3b0f-11ea-9630-61ff4f657dd2.png)

After warping for a while, we obtain the following on 1951-03-17.  Note how quite a few craters on the dark side are lit.  Also note how the bottom half of the terminator is completely lacking in crater lightning, and how the craters at the top of the picture look like they are lit from the top, while the Sun is on the right:

![screenshot44](https://user-images.githubusercontent.com/7423020/72689315-7ebc3300-3b10-11ea-99f2-34924e515c76.png)

Let's compare this with the [vanilla RSS textures](https://github.com/KSP-RO/RSS-Textures/blob/master/8192/Moon_NRM.dds).  Here is an image on 1951-01-01.  The craters are properly lit from the bottom:

![screenshot45](https://user-images.githubusercontent.com/7423020/72751604-568c0d00-3bc0-11ea-906b-4956741d818e.png)

Now here is an image on 1951-03-17.  All the craters are properly lit from the right, and there is very little light on the dark side of the Moon:

![screenshot47](https://user-images.githubusercontent.com/7423020/72751795-dade9000-3bc0-11ea-9235-e44c914d2d6b.png)

I have no idea what is the root cause, but note that the normal maps are properly aligned with the craters (i.e., they attempt at generating highlight and shadows at the right place) but they catch light in the wrong direction.  Could this be due to a swap between x and y?

**Comment by Vannadin** [comment]
thank you for detailed explanation. i tried every normal map solution. single channel, two channel, invert x, invert y, swap x and y.. but well.. not worked. 


aaaaaah ok i figured out.
usually, two channel normal map uses R and G as X and Y normal map. but in this case, RGB is Y axis and additional alpha map is used for X axis normal map. i have no idea why they did like this, even though there is a better way to reduce file size. funny thing is all normal map textures are using different solutions.
