### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by WC12366** [mockingbirdnest/Principia#2470]
When I use this config together with Principia and RealExpansion, the game crashed.
[RealExpansion.zip](https://github.com/mockingbirdnest/Principia/files/4195952/RealExpansion.zip)
but when I move the Eris node in the principia config to the RealExpansion config, all thing works well.

**Comment by pleroy** [comment]
Will you tell us what the issue is exactly?  Please give us the [logs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs).

One of your config files has `FOR[Principia]` and the other has `AFTER[Principia]`.  Seems inconsistent to me.

**Comment by WC12366** [comment]
Oh, sorry. I didn't noticed this. When I change both of them to FOR[Principia], all thing works well again.

**Comment by WC12366** [comment]
But it seems thar the new verson  of Principia removed the Eris node. So I may add the Eris config manually.

**Comment by pleroy** [comment]
Eris is [still](https://github.com/mockingbirdnest/Principia/blob/master/astronomy/sol_gravity_model.cfg#L413) [there](https://github.com/mockingbirdnest/Principia/blob/master/astronomy/sol_initial_state_jd_2433282_500000000.cfg#L77) I think.

**Comment by WC12366** [comment]
Thank you.
