### ISSUE TITLE
Mark Station keeping to be broken with Principia

### ISSUE THREAD

**Issue by DarthPointer** [mockingbirdnest/Principia#2515]
For some reasons I've tried to maintain a simple CommSat group positions with Station Keeping. It has resulted into it telling me that there was not enough fuel despite I have had about 100m/s of delta vee and I have asked just a small tweak. It has also taken all the fuel from the tanks :(

Please mention Station Keeping as never-to-be-used in FAQ.

It would be also nice to be able to make slight trajectory corrections via tracking station (slightly decrease orbital period of a satellite, if it has a somewhat stable orbit)

**Comment by eggrobin** [comment]
Any mod that does tries to move vessels or otherwise change orbits without using engines outside time warp, which is the only stock non-cheat way to do that, is incompatible with Principia.

Many mods do that, and they are as a consequence all incompatible with Principia.
While we do our best to document high-profile incompatibilities, we cannot really know about all of them; I had never heard of that StationKeeping thing.

Mod users are advised to think about possible incompatibilities when using multiple mods.

**Comment by pleroy** [comment]
I have added @eggrobin's reply to the [FAQ](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#compatibility-with-other-mods) as a general statement to which we can refer users: it seems more useful to document the underlying reasons why a mod may be incompatible with Principia, than to have a (necessarily incomplete) laundry list of mods.
