### ISSUE TITLE
Add/Subtract 1 Orbit in the flight plan editor

### ISSUE THREAD

**Issue by GianniJohn** [mockingbirdnest/Principia#2517]
Hi,

I have a suggestion for the flight plan: Implement a way to add/subtract 1 Orbit in the flight plan editor (like in the stock manoeuvre nodes).

**Comment by pleroy** [comment]
There is not really a notion of "orbit" in N-body physics.  What would make sense though is to extend the flight plan to the next "interesting" point (Ap/Pe for instance).

**Comment by eggrobin** [comment]
> What would make sense though is to extend the flight plan to the next "interesting" point (Ap/Pe for instance).

This would fail in a lot of common cases (e.g., low-inclination or low-eccentricity orbits) where the locally interesting points are not globally interesting (because higher-order effects dominate over the variations induced by the underlying Keplerian orbits).

On the other hand, the [orbit analyser](https://github.com/mockingbirdnest/Principia/wiki/Orbit-analysis) provides us with several different notions of *one revolution*—the term *one orbit* is improper—: one anomalistic period, if you care about apsides, one nodal period, if you care about nodes, one sidereal period (possibly less useful).
It could likely also be useful to have some synodic periods (e.g. moving an ejection burn to the next revolution, maintaining a constant ejection angle).

In any case, a prerequisite for doing anything here would be to have some sort of integration between orbit analysis and flight planning.

**Comment by eggrobin** [comment]
> In any case, a prerequisite for doing anything here would be to have some sort of integration between orbit analysis and flight planning.

We have that since #2848, in Germain.

> It could likely also be useful to have some synodic periods (e.g. moving an ejection burn to the next revolution, maintaining a constant ejection angle).

This could be useful, but it requires celestial orbit analysis, which we have so far punted.

[Discord discussion](https://discord.com/channels/319857228905447436/480397772248580098/997805815358554172):
> <@RCrockford>  For 2517 even just bumping the orbit by one period would be useful even if it didn't keep the exact ejection angle, it would get you pretty close in one click. 
> <@eggrobin>  Yeah, probably the nodal period would be a good general-purpose default; and then someday we could change that depending on the plotting frame for constant ejection angle if you are in HCI or GSE.

(Likewise MEO would be a hint that you want +1 synodic revolution wrt the moon.)
