### ISSUE TITLE
Add daylength tweakable

### ISSUE THREAD

**Issue by DarthPointer** [mockingbirdnest/Principia#2520]
I play with JNSQ, one of its minor effects is a 12 hour long day. The planner assumes day to be the "default" one - 6h per day. It brings some inconvenience in planning, I would like to have a 12 hours day in the planner too. It can be a number in a .cfg or a field in planner, does not really matter where we change this parameter. I guess it is a simple-to-do QoL and want to see it in the next release.

**Comment by pleroy** [comment]
Adding a random piece of configuration to change random parameters is a recipe for endless confusion, both for us and for users.

It's more interesting to figure out if we could just "do the right thing" automatically.  It's not only JNSQ that has that problem: there is probably a similar issue with RSS using [RSSTimeFormatter](https://github.com/KSP-RO/RSSTimeFormatter).

It seems that [JNSQ is embedding](https://github.com/Galileo88/JNSQ/tree/master/GameData/JNSQ/JNSQ_Plugins/Kronometer) [Kronometer](https://github.com/Kopernicus/Kronometer).  Kronometer seems to be [installing its own date formatter](https://github.com/Kopernicus/Kronometer/blob/e2d59e7a0f759b47f2c999dce00265a81ed45d14/src/Kronometer.cs#L77) which I guess we could use to format dates and times instead of doing our own thing.

Where it gets tricky is that, when editing the flight planner, we need to parse dates and times, and Kronometer doesn't seem to provide services to do that.  We could parse the Kronometer `ConfigNode` but that's going to be horrendously brittle.  Maybe the best we can do is to access the `Kronometer.SettingsLoader` object through reflection.

Pinging @Sigma88 and @StollD in case they have insights to share.

**Comment by Sigma88** [comment]
I don't know what "the planner" is

Kronometer changes the stock definition of year and day which are accessible to any mods.

if "the planner" is a mod, then just read the definitions of day and year instead of hardcoding the length

if "the planner" is a stock thing, then I guess they decided to hardcode the number instead of using their own variables...  that wouldn't surprise me

**Comment by DarthPointer** [comment]
Other mods (kerbalism, KAC) see it and use 12h day.

**Comment by pleroy** [comment]
Clarification: the flight planner is a UI in the Principia mod that has fields where you enter the durations of burns and the durations between burns.  We parse the string given by the user, and at the moment we pick 6- or 24-hour days depending on `GameSettings.KERBIN_TIME`.

**Comment by pleroy** [comment]
@Sigma88: Thanks for the info, I know what to do now.

**Comment by Sigma88** [comment]
nice!

feel free to ping me if you need anything else
