### ISSUE TITLE
Make orbital analysis window available in tracking station

### ISSUE THREAD

**Issue by DarthPointer** [mockingbirdnest/Principia#2531]
[Description by @eggrobin, this issue originally had none]
The orbit analyser is currently only available in map view.

We should make it available for the `PredictedVessel`, i.e., the selected vessel in the tracking station, and the active vessel in map view.

**Comment by DarthPointer** [comment]
Improved level: add abillity to analysis of a user-defined orbit. For example, I wish to know which orbit to choose for a retranslator - I input desired "initial" orbit data and see if it is any stable before I launch the vessel.

**Comment by eggrobin** [comment]
> Improved level: add abillity to analysis of a user-defined orbit. For example, I wish to know which orbit to choose for a retranslator - I input desired "initial" orbit data and see if it is any stable before I launch the vessel.

One issue at a time. This issue is about making the orbit analyser available in the tracking station, not about every imaginable orbit analysis-related improvement.

This suggestion, much like, e.g., the idea of planning prior to launch, would require a complete rework of the UI and major changes to the underlying data model to describe trajectories without starting from the trajectory of a pre-existing vessel.
