### ISSUE TITLE
Apocalypse Maybe?

### ISSUE THREAD

**Issue by LUH5147** [mockingbirdnest/Principia#2617]
My Setup
Win7 x64, i5-4460, 16GB,
KSP 1.8.1
OPM 2.2.6
Principia Galileo
Kopernicus-1.8.1-1
Module Manager 4.1.3.dll
I have other addons, but they shouldn't be relevant to these issues (famous last words).

Issue1: The error states "New Apocalypse: INVALID_ARGUMENT: Error extending trajectory for Laythe". All well and fine BUT Laythe has been patched out of the system.  (Refer to OPM_Patch.cfg.txt). If I pull the principia folder out of \GameData\ (and put it on the desktop), fire up KSP and visit the Jool system, I have Pol, Bop, Tylo, and Vall (no Laythe). If I drag the folder back under \GameData\ and fire up KSP (no other changes), I get the above listed error message.  Now if you go to the Jool system, only Pol and Tylo are around (I hear that Bop and Vall have separation issues). (Refer to retrobop.cfg.txt)  With Laythe patched as shown, Principia is either causing the patching sequence to change or mis-IDing the real culprit.  The only errors I have had with the Principia install and setup was the missing VC++ 2015 which was quickly fixed. I have also included the Principia journal file for diagnostics.

Issue2: Principia user settings are not persistent.  I set the checkboxes 'display patched conics' and sun-centric viewpoints.  After every shutdown and restart the patched conics checkbox is cleared and the viewpoint goes back to kerbin-centric.

Reproduceability: Both issues occurs consistently at startup.

[OPM_Patch.cfg.txt](https://github.com/mockingbirdnest/Principia/files/4843207/OPM_Patch.cfg.txt)
[retrobop.cfg.txt](https://github.com/mockingbirdnest/Principia/files/4843208/retrobop.cfg.txt)

[ERROR.20200628-200223.6944.log](https://github.com/mockingbirdnest/Principia/files/4843216/ERROR.20200628-200223.6944.log)

[WARNING.20200628-200223.6944.log](https://github.com/mockingbirdnest/Principia/files/4843204/WARNING.20200628-200223.6944.log)

[JOURNAL.20200628-200223.log](https://github.com/mockingbirdnest/Principia/files/4843205/JOURNAL.20200628-200223.log)

**Comment by pleroy** [comment]
1. You need to start a new save after you apply a patch or otherwise change the configuration of your system.  The configuration of the solar system is part of the save, so what you are seeing is that the original configuration of your solar system indeed has Laythe colliding with some other celestial.

1. The "patched conics" setting is not persisted on purpose.  It's there for educational purposes to let you compare *n*-body trajectories with conics, but if you are using it systematically, you're holding it wrong.  The reference frame is persisted, but it's associated with each vessel.  When you don't have an active vessel, it reverts to a default frame.
