### ISSUE TITLE
Game Crashes When Launching New Game (RO-RP-0) 

### ISSUE THREAD

**Issue by clc333** [mockingbirdnest/Principia#2643]
I have zero experience with this mod. Additionally the information out there regarding this is hard for me to find given I'm not in the "loop" on this yet. With this said, whatever logs or information required to help assist please guide me to their respected directories so I can provide them. 

I'm running RO-RP-1 with its supporting required mods. I can provide a full mod list if required but I have no deviated from the core of the install instructions with RO.

**Comment by clc333** [comment]
I'm running on windows x64.

**Comment by eggrobin** [comment]
> Additionally the information out there regarding this is hard for me to find

There is an [FAQ](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions). There is also a [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/162200--).

> Duplicate config |principia_gravity_model| (Principia/real_solar_system/gravity_model/principia_gravity_model, Principia-master/astronomy/sol_gravity_model/principia_gravity_model)

The mod was improperly installed, it sounds like you have multiple copies of the configuration files.

> the Master Principia folder

I am not entirely sure what you are referring to, but if you downloaded the source code repository at master and somehow shoved that into your game, you are holding it wrong; that is not how you install KSP mods, and this is not specific to Principia.

The installation instructions are [in the FAQ](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#installing-principia).
Follow them, and don’t do random other things.

**Comment by clc333** [comment]
Fixed Just had to delete the master folder, as stated above just a copy of a single config was conflicting. And Yes I know there is a FAQ but the information is rather generalized and overbearing. I'm was looking for a more specific answer such you provided and this issue has been resolved without me having to go through a lot of information or misunderstanding said information. As for the last statement. Restating that it is installed incorrectly is well stating the obvious, I was looking for a solution EI yes you are not suppose to have the master folder present and this is why. I would encourage you to provide a method for solution for future help as just restating the issue isnt helpful. 

"I am not entirely sure what you are referring to, but if you downloaded the source code repository at master and somehow shoved that into your game, you are holding it wrong; that is not how you install KSP mods, and this is not specific to Principia."

The statement that's not how you install mods is pretty obviously with me posting here to begin so restating said fact isn't helpful. Just wanted to point that out for future people who need help so they actually get solutions and not restatements of their issues.

**Comment by eggrobin** [comment]
>  I know there is a FAQ but the information is rather generalized and overbearing.

The FAQ is definitely quite long, and a bit daunting. We are open to suggestions for making the installation instructions easier to understand; while they are quite prominent in the FAQ page itself, it seems that this did not do the job.

I have two questions:
1. which pages did you look at?
2. what led you to download this master folder?

A word of warning though: although its installation process is fairly typical, the actual gameplay of this mod is very different from stock KSP; you will likely have a hard time making sense of it without reading the documentation.

---

As for your remarks on restating the obvious, I am happy to hear that it was obvious to you that you had misinstalled the mod.

It was not at all obvious to me that you knew that, since you believed that you had
> no deviated from the core of the install instructions with RO

and since, this being a bug tracker, most of the issues opened here are errors in Principia, rather than setup errors.

Another thing that was not obvious to me (as conveyed by my use of the words “not entirely sure”) is what you had actually done; you did not describe the steps you had followed, and the installation instructions do not involve a Master folder, so I had to infer from your second comment that you somehow downloaded the source code repository (possibly via `Code > Download ZIP`? I never use this; I guess it gives you a folder named after the branch?).

That which is obvious to you is not always obvious to others; that which looks to you like restating what you said may be a clarification to others. Keep in mind that I am not the only developer of this mod: issue comments are also a channel for communication between developers, and clarifying everything that is understood about an issue is critical to avoid wasting time diagnosing it multiple times.
