### ISSUE TITLE
Showing "d6" instead of "d" in every countdown of UI

### ISSUE THREAD

**Issue by sgdxbc** [mockingbirdnest/Principia#2714]
![image](https://user-images.githubusercontent.com/59077595/92409861-aed64600-f174-11ea-8a3f-9079dc274190.png)

As shown in the image, countdown times are shown as "x d6 x h x min xx.x s", and it feels strange to use "d6" instead of "d" for days.

Is it intended as a remainder to "6 hours per day"? (I think not because it's not the case in the demo of wiki.)  Is there any config to change it?

**Comment by eggrobin** [comment]
> Is it intended as a remainder to "6 hours per day"?

It is.

`d` is used if you use 24-hour days (there is a setting for that in KSP).

**Comment by pleroy** [comment]
More precisely `d` is followed by a digit if there are less that 10 hours in a day.  Thus `d3`, `d6`, `d9` are all possible.  Above 10 hours it's just `d`.  That would be the case for JNSQ and RSS, for instance.

No config to change this because the more config options we have the harder it is to maintain.  (It's not only formatting it's also parsing, e.g., when editing durations in the flight plan.)

**Comment by sgdxbc** [comment]
Thanks for explanation.
