### ISSUE TITLE
KSP Principia crashes when loading or starting game with RSS installed

### ISSUE THREAD

**Issue by taiwanluthiers** [mockingbirdnest/Principia#2757]
The game crashes when I attempt to start or load a game when RSS is installed. Any other mod works fine but as soon as RSS is loaded the game will start normally, but once I start any new game, or load an existing game, the program freezes then crashes. 

This is the log files:
[ERROR.20201008-214921.31832.log](https://github.com/mockingbirdnest/Principia/files/5349273/ERROR.20201008-214921.31832.log)
[FATAL.20201008-215017.31832.log](https://github.com/mockingbirdnest/Principia/files/5349274/FATAL.20201008-215017.31832.log)
[INFO.20201008-214921.31832.log](https://github.com/mockingbirdnest/Principia/files/5349276/INFO.20201008-214921.31832.log)
[WARNING.20201008-214921.31832.log](https://github.com/mockingbirdnest/Principia/files/5349278/WARNING.20201008-214921.31832.log)

**Comment by eggrobin** [comment]
> as soon as RSS is loaded the game
> load an existing game

You cannot load a non-RSS game with RSS, you must create a new one; this is because installing RSS means the set of celestial bodies changes, and Principia requires that it remain the same.

This is what is happening in the logs you gave.

This is not your only issue though, since you are running into a crash when starting a new game as well.
Unfortunately, you did not provide logs from a crash resulting from starting a new game, so I am mostly left guessing as to what goes wrong there.

Are you perhaps using an extension mod that adds more celestial bodies, e.g., RealExpansion?
Since we have tailored configurations for RealSolarSystem, any extensions to RSS need to come with extensions to the Principia configuration files in order to be Principia-compatible.

**Comment by taiwanluthiers** [comment]
I am not. I even tried disabling mods one by one, wiping all mods and reinstalling, and whenever RSS is installed, the game crashes. 

I'm going to start a new game and see what it says.

I only installed RSS and whatever dependencies it requires (like kopernicus).

It adds no new planet or anything, just RSS. So no idea what exactly is going on.

**Comment by taiwanluthiers** [comment]
I started a new game, this fixed it.

I think the reason it crashed before is because I had Real Exoplanets installed.

I tried using the SLIPPIST-1 mod but that mod won't support 1.8.1, is there a version that does?

**Comment by eggrobin** [comment]
> I tried using the SLIPPIST-1 mod but that mod won't support 1.8.1, is there a version that does?

Ask @gregroxmun; I think [this](https://forum.kerbalspaceprogram.com/index.php?/topic/157020-173-seven-worlds-around-slippist-1-v080-update-august-8th-2019/page/4/&tab=comments#comment-3752076) was his latest update on the matter.

> I had Real Exoplanets

Note that interstellar travel is effectively impossible with Principia, and as a result multiple star systems are not supported.
You should either use RSS (for our solar system) or SLIPPIST-1 (for the TRAPPIST-1 system), not both.
