### ISSUE TITLE
Wrong contract orbits in map view(in RSS)

### ISSUE THREAD

**Issue by Mirviy** [mockingbirdnest/Principia#2769]
I have two contracts that let me launch satellites into defined orbits around the moon. But the orbits shown on Map view will change when SOI changes. (So I can't pre-adjust my trajectory before captured by Moon.)
Before captured by Moon:
![screenshot658](https://user-images.githubusercontent.com/24671039/97049991-2d653680-15af-11eb-85d7-b83f0bc55b30.png)
After captured:
![screenshot659](https://user-images.githubusercontent.com/24671039/97049982-2b9b7300-15af-11eb-9ac2-c81168292f13.png)

**Comment by pleroy** [comment]
This is due to the support of axial tilt in Principia.  The reference plane of game coordinates changes as the main body does (it is the equator of the main body).  The stock orbits are defined by a fixed inclination with respect to that reference plane and therefore change when the reference plane does.

Ultimately this kind of contract is at heart incompatible with Principia even besides the axial tilt effects.  See [this](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip181-191-1101-principia%E2%80%94version-gauss-released-2020-10-16%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&do=findComment&comment=3788715) and [this](https://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip181-191-1101-principia%E2%80%94version-gauss-released-2020-10-16%E2%80%94n-body-and-extended-body-gravitation-axial-tilt/&do=findComment&comment=3789232) note on the forum for details.
