### ISSUE TITLE
Crash while descending towards the surface of a body

### ISSUE THREAD

**Issue by RCrockford** [mockingbirdnest/Principia#2811]
A fairly repeatable crash while undergoing powered descent towards the surface of the Moon.

```Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FF82D1E640F  	google::LogMessageFatal::~LogMessageFatal [0x00007FF82D1E640E+46] (C:\Users\rcrockford\Documents\GitHub\Google\glog\src\logging.cc:2109)
    @   00007FFFF34A9214  	principia::astronomy::internal_orbit_recurrence::OrbitRecurrence::OrbitRecurrence [0x00007FFFF34A9213+675] (C:\Users\rcrockford\Documents\GitHub\Principia\astronomy\orbit_recurrence_body.hpp:27)
    @   00007FFFF34B93B3  	principia::ksp_plugin::internal_orbit_analyser::OrbitAnalyser::RepeatedlyAnalyseOrbit [0x00007FFFF34B93B2+4834] (C:\Users\rcrockford\Documents\GitHub\Principia\ksp_plugin\orbit_analyser.cpp:163)
    @   00007FFFF34B1DAF  	std::thread::_Invoke<std::tuple<`principia::base::internal_jthread::MakeStoppableThread<`principia::ksp_plugin::internal_orbit_analyser::OrbitAnalyser::Restart'::`2'::<lambda_1> >'::`2'::<lambda_1>,principia::base::internal_jthread::stop_token>,0,1> [0x00007FFFF34B1DAE+78] (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\thread:43)
    @   00007FF84D8410B2  	beginthreadex [0x00007FF84D8410B1+321]
    @   00007FF84E637C24  	BaseThreadInitThunk [0x00007FF84E637C23+19]
    @   00007FF84FCCD4D1  	RtlUserThreadStart [0x00007FF84FCCD4D0+32]
F1204 18:28:54.317481 13504 orbit_recurrence_body.hpp:27] Check failed: Sign::OfNonZero(??) == sign_C?? (- vs. +) [-2147483648; -2147483648; 1]
```

[Journal](https://1drv.ms/u/s!ApWZXOEZJxA5gppbL35Ser1rYOprPA?e=ouLULq)
[Log](https://github.com/mockingbirdnest/Principia/files/5645418/INFO.20201204-181807.14660.log.zip)

Note, this occurred on a locally created build.

**Comment by eggrobin** [comment]
I can’t trivially decode the stack with our usual script since this is a custom build, but since it runs on the machine where it was built it comes with symbols already so all is well.

We end up here with νₒ = Dᴛₒ = -2147483648, Cᴛₒ = 1, which is obviously a problem:
https://github.com/mockingbirdnest/Principia/blob/eb888617403f9e0aa6780f077441bd5e62115782/astronomy/orbit_recurrence_body.hpp#L20-L28

The call is here, so the -2147483648 is probably UB from a non-representable `double` to `int`.
https://github.com/mockingbirdnest/Principia/blob/eb888617403f9e0aa6780f077441bd5e62115782/astronomy/orbit_recurrence_body.hpp#L74-L76

We should probably be using 64-bit integers in general, but here there is something more worrying.
https://github.com/mockingbirdnest/Principia/blob/eb888617403f9e0aa6780f077441bd5e62115782/astronomy/orbit_recurrence.hpp#L67

At first glance it seems that 2147483648 orbits per day would still be 24855 orbits per second, which is too much (even if the orbit goes underground, since the spacecraft being analysed is above ground, the orbit cannot be shorter than the time required to fall to the centre of the Earth).

However, note that κ is computed as https://github.com/mockingbirdnest/Principia/blob/eb888617403f9e0aa6780f077441bd5e62115782/astronomy/orbit_recurrence_body.hpp#L53-L59 and recall that https://github.com/mockingbirdnest/Principia/blob/eb888617403f9e0aa6780f077441bd5e62115782/astronomy/orbit_recurrence.hpp#L29-L37
so that for an orbit with a very high nodal precession Ωʹᴛ, the “day” would be very long, and thus it is possible that we are indeed reaching those numbers with the underground orbits of descent.

**Comment by RCrockford** [comment]
Worth nothing that this occurred above the Moon as such the "day" is longer to start with, also the "orbit" had a high apoapsis approximately 10 Mm above the surface hmm. I suspect that this ties in with your analysis.

**Comment by eggrobin** [comment]
Hm, I am very puzzled, replaying the journal (removing the pointer consistency checks and forcing all analysis requests to be executed by peppering the analyser with `join`s) I am unable to replicate the check failure, and the highest value of κ I observe is 6.2894…

**Comment by eggrobin** [comment]
On second thought the hypothesis according to which we are analysing underground orbits does not make much sense, considering that the integrator should stop when we are underground.

**Comment by eggrobin** [comment]
It seems that this is instead plain old UB, we are accessing a vector at index -1.

**Comment by eggrobin** [comment]
This in turn happens because the sidereal period is negative (`-3.82112421336217958e+04 s`, about -10 h 37 min).

**Comment by eggrobin** [comment]
The sidereal period is negative because the trajectory is absurd.
In the figure below, the trajectory being analysed is shown as black points every 10 s, as computed; the sphere of radius `min_radius` (below which a collision is certain) is shown in white, and the sphere of radius `0.99 * min_radius` (below which the integrator returns an erroneous status to avoid propagating a corrupt state) is shown in red.
![2811](https://user-images.githubusercontent.com/2284290/101812552-c9c1a900-3b1b-11eb-8c79-a8d82fb7bd18.png)
Far below the surface, the trajectory takes a sharp bend (the timestep is likely too small for the multistep integrator this deep in the gravity well; that kind of integrator does not behave nicely under those circumstances).

We should make the analyser robust to weird trajectories; we should also check if we can make the integrator stop when the force computation is erroneous (instead of continuing before returning an erroneous status) without running into performance issues.
