### ISSUE TITLE
Frequent crashes when staging procedural fairings

### ISSUE THREAD

**Issue by Amselfass** [mockingbirdnest/Principia#2931]
Good afternoon,

I am experiencing Principia crashes when staging procedural fairings. These crashes are frequent (I would say about 20 % of my fairing separations result in a crash) but unfortunately not reproducible at will (i.e. I cannot identify a set of vessel properties or flight parameters that will always / never produce a crash).

The crash occurs on pressing spacebar when the next stage has a procedural fairing separation in it. It instantly crashes to desktop, with no Windows dialog boxes shown. The Unity Crash Handler does not show. There is no KSP crash log produced in %LocalAppData%/Temp/Squad/Kerbal Space Program/Crashes.

My KSP version is 1.10 and I am using Principia version Goldbach. However, I already experienced the same issue with KSP 1.8 and Principia Гельфонд.

Here are the [.FATAL and .INFO files.](https://gist.github.com/Amselfass/e1b0e43c3948471b539feaebc46bb002)

I have also produced [a journal file](https://drive.google.com/file/d/1l1HeXhdRU3qI7Pa-VEzQKCTDMuE__3zg/view?usp=sharing) (caution: 1 GB download!).

Please let me know if you require further information.

**Comment by sohmien** [comment]
I also had such crashes, but didn't know it was caused by Principia. My solution was to disable fairing decouplers, so that the interstage decouples with the fairings still attached. This way the game doesn't crash.

**Comment by pleroy** [comment]
I was able to replay the journal and reproduce the bug.  No idea what's going on yet.

**Comment by pleroy** [comment]
So this is a segue of #2507, with variations.

In #2507 we were trying to insert points before the beginning of the psychohistory when parts moved from one vessel to another.  This could happen if the adaptive-step integrator would generate multiple points in a short period of time, e.g., because of high accelerations due to collisions.

In this issue we are trying to insert points before the beginning of the history.  How can this happen, you ask, when the history is using a fixed-step integrator?  Well, not always: when burning we directly copy the psychohistory to the history, and *it* is using an adaptive-step integrator.  So if you have high collisions *and* are burning you may end up in this situation.

@Amselfass, thanks a lot for taking the time to send us a journal, it would have been impossible to debug without it.
