### ISSUE TITLE
Crash after loading screen with ksp 1.10

### ISSUE THREAD

**Issue by Malekit300** [mockingbirdnest/Principia#3038]
Hi i really like Principia in 1.8.1 
i would like to use in 1.10 but after loading screen just when the screen appear with kerbonaute and kerbin behind, the game crash 2 sec after 
I try a new game without any patch ---> crash 
what i can do  ?

**Comment by pleroy** [comment]
Well, you are not giving us a lot of information (no log files, no screenshots, no crash dump) but the most likely problem is that either your KSP or your Principia is incorrectly installed.  I mean, we have been supporting 1.10.1 since September without any trouble.

Note that the original 1.10 release is not supported, you'll need 1.10.1 or 1.11.x.  Also make sure that you download the latest version of Principia (Gröbner) and that you actually download the binary and not the source code (people sometimes get confused).

**Comment by pleroy** [comment]
No life signs, closing.
