### ISSUE TITLE
Pricipia - Extraterrestrial Launchpads Intolerance?

### ISSUE THREAD

**Issue by ThisisShoo** [mockingbirdnest/Principia#3077]
The game freezes when I finalize the construction of a new ship (a process where a new physically interactable vessel appears attached to EL's construction module, which then can be released). Since the last save is always before the point of release, this issue practically renders EL ineffective as a mod. 

The Principia version is Grossmann, and EL is the latest version that was compatible with game version 1.8.1.

**Comment by graptis** [comment]
I can confirm the same issue with both any version of Extraplanetary launchpads or principia I tried, and Global Construction as well.
The additional info I can volunteer is that this issue can be worked around, albeit awkwardly, by effectively disabling principia before finalise of the new ship using "hack gravity" in the cheat menu and then re-enabling it (in which case it appears to work fine), which points to the possibility that something weird happens at the point in time of the finalization (when - I assume! - Unity adds the new craft).
I also tried with a debug build of principia and tried to debug a little bit but couldn't get very far due to time and effort constraints, but it looks to me like the new ship is "in a weird state" for a frame or so causing principia to crash (I got a "part Id is zero" assertion or something).
I hope this helps.

**Comment by ThisisShoo** [comment]
> I can confirm the same issue with both any version of Extraplanetary launchpads or principia I tried, and Global Construction as well.
> The additional info I can volunteer is that this issue can be worked around, albeit awkwardly, by effectively disabling principia before finalise of the new ship using "hack gravity" in the cheat menu and then re-enabling it (in which case it appears to work fine), which points to the possibility that something weird happens at the point in time of the finalization (when - I assume! - Unity adds the new craft).
> I also tried with a debug build of principia and tried to debug a little bit but couldn't get very far due to time and effort constraints, but it looks to me like the new ship is "in a weird state" for a frame or so causing principia to crash (I got a "part Id is zero" assertion or something).
> I hope this helps.

After you used the "hack gravity" method, would you pass the new ship as normal? Will the fact that you disabled gravity in orbit affect the craft's trajectory?

**Comment by graptis** [comment]
I assume there is no discernible effect one way or the other, as "hack gravity" does not disable gravity (unless you use the slider to take it to zero), only "relinquish control" from principia back to KSP patched conics. Technically, the orbit would be different the more you leave it hacked (as it is only taking into account the gravity of the main orbited body), but I believe the difference would be in the order of millimeters or so, probably less than the interaction of the new craft being released and pushed from your construction dock.

**Comment by graptis** [comment]
I am not sure what you mean by "pass the new ship", but they are fully functional. You can release it with or without hacked gravity. Usually though because things sometimes get unstable with EL, I keep a save before finalise and after releasing a new ship, and usually load from the point of release just to be sure.

**Comment by ThisisShoo** [comment]
> I am not sure what you mean by "pass the new ship", but they are fully functional. You can release it with or without hacked gravity. Usually though because things sometimes get unstable with EL, I keep a save before finalise and after releasing a new ship, and usually load from the point of release just to be sure.

I was just wondering if something about the new ship will be different, because you mentioned something about "in a weird state". Forgive my absolute ignorance in modding KSP. Thank you for providing that workaround, I would never have thought about that.

**Comment by graptis** [comment]
My personal opinion would be to keep this open if the author's agree because the workaround is exactly that - a workaround. If it is possible to actually fix this issue it would be better.

**Comment by pleroy** [comment]
This is looking quite similar to [EL issue #157](https://github.com/taniwha/Extraplanetary-Launchpads/issues/157), which unfortunately didn't make much progress.
