### ISSUE TITLE
Principia uses icon color instead of orbit color

### ISSUE THREAD

**Issue by Bellabong** [mockingbirdnest/Principia#3078]
So this is pretty minor but I noticed that if Kopernicus has defined an icon color for a body that Principia uses the icon color instead of color to colour its orbit.

Principia colours:
https://i.imgur.com/Xbl1AAz.png

Actual orbit colours:
https://i.imgur.com/Ej5Duv9.png

**Comment by eggrobin** [comment]
I had a vague recollection of difficulties with the colours; poking at this I found it again: `celestial.orbitDriver.orbitColor` is not the right color (it is white for all planets, instead of being the colour of the stock orbits). I think the icon colour (specifically, `celestial.MapObject.uiNode.VisualIconData.color`) was the first thing I found that _was_ the right colour in stock and RSS.

It seems instead I should be using `celestial.orbitDriver.Renderer.orbitColor`. At least that has the colour of the stock orbit in stock and RSS; KSP being KSP I don’t know whether it’s actually secretly the icon colour.

I’ll let you check that #3135—to be released in Hadamard, Wednesday—fixes the issue.
