### ISSUE TITLE
Dll error when loading the game

### ISSUE THREAD

**Issue by ThisisShoo** [mockingbirdnest/Principia#3229]
The author of Tweakscale redirected me here because apparently an issue raised by Tweakscale is somehow linked to some dll errors with Principia.

See details on https://forum.kerbalspaceprogram.com/index.php?/topic/179030-130/&do=findComment&comment=4063368

**Comment by pleroy** [comment]
The messages related to Principia are normal, and documented in the [FAQs[(https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#the-case-of-badimageformatexception).  I don't know what your problem is, but Principia is not the cause.

**Comment by Lisias** [comment]
Hi, @pleroy .

I have a suggestion to get rid of that DLLs messages. Since you are loading the DLL yourself, they can be anywhere in the folder, so move them into a directory called `PluginData`. KSP ignores anything inside directories named `PluginData`.

TweakScale itself does this - there're some DLLs that are compiled to specific KSP versions, and I put them inside a `PluginData` directory, and then load just one of them by hand.
