### ISSUE TITLE
game crashes right after loading screen

### ISSUE THREAD

**Issue by GeorgeBush26** [mockingbirdnest/Principia#3255]
My game keeps crashing right after I load into the game itself, not a save, Principia is the correct version and is in the game data folder. Please help!

**Comment by AirstrikeIvanov** [comment]
This appears to be due to the most recent update to KSP. My latest FATAL log shows this line:

`F1225 16:38:53.564429 10580 C:\Users\phl\Projects\GitHub\Principia\Principia\ksp_plugin_adapter\ksp_plugin_adapter.cs:324] Unexpected KSP version 1.12.3; this build targets 1.8.1, 1.9.1, 1.10.1, 1.11.x, and 1.12.2.`

**Comment by GeorgeBush26** [comment]
thank you so much
