### ISSUE TITLE
Investigate the possibility to display equipotential lines

### ISSUE THREAD

**Issue by pleroy** [mockingbirdnest/Principia#3358]
What I have in mind is [something like this](https://static.scientificamerican.com/sciam/cache/file/799B2D41-709C-4511-9D60A3E4B946DB55_source.png?w=590&h=800&5081446F-BF42-45E4-89D85528A2C70365).  There are many interesting challenges, though, in particular (1) how insanely costly is that going to be? (2) what kind of weird UI do we need to let the user pick what they want?

Of course, this may not pan out, but it seems rather interesting.

**Comment by pleroy** [comment]
Equipotentials in the Earth-Centred reference frame that fixes the direction of the Moon (backward from the in-game MEO).
![equipotentials](https://user-images.githubusercontent.com/7423020/168495207-bfcd05ea-325a-4789-af49-6e952413aa32.gif)

**Comment by eggrobin** [comment]
Note on visualization: the equipotentials move (and the energy of a free-falling vessel can change over time, because since the potential is time-dependent, so that Noether’s theorem does not apply).
This means, for instance, that if we draw the equipotential of the vessel at any point in time, the vessel may be seen to cross its own equipotential, defeating the point of drawing equipotentials. This is not unlike a trajectory going through the current position of the moving Moon. However, in that case, the motion of the moon is indicated by its trajectory (a faded line in the past, a solid line in the future).

We may want to similarly draw the equipotential of the vessel’s energy at multiple points in time, so that any motion is evident. As usual, it is best to work in a reference frame wherein things you care about don’t move, but that requires being able to see whether they move.

**Comment by eggrobin** [comment]
Update: The equipotentials move too much in all our current frames to be of any practical use, and would thus only clutter and confuse.

In particular, in the MEO frame, the shape of the potential changes drastically over a month, obscuring most of the Lagrange points.

The animated GIF from https://github.com/mockingbirdnest/Principia/issues/3358#issuecomment-1127054011 is more promising: the Earth is close to the barycentre, so this potential is nearly the one that would have the Lagrange points, absent the Sun; they are still legible here. However, because the orbit is eccentric, the potential grows and shrinks over the course of a month, making trajectories that stay near a Lagrange point appear to move away and fall into the Moon's well.

It may be time to seriously look into the long-discussed rotating-pulsating frame, wherein the potential should look much the same.

**Comment by eggrobin** [comment]
> It may be time to seriously look into the long-discussed rotating-pulsating frame, wherein the potential should look much the same, but the Lagrange points don’t move.

Indeed, while the total potential wobbles a little bit because of the sun, the Lagrange points (especially L_1 and L_2) are legible.

![EarthMoonLagrange 20230123](https://user-images.githubusercontent.com/2284290/213957618-c1019869-24b4-458c-bac4-b4920214bd3b.gif)
