### ISSUE TITLE
Visual glitch with RSS/Principia.

### ISSUE THREAD

**Issue by mark260486** [mockingbirdnest/Principia#3391]
Hi, all!

I've installed KSP 1.12.3 from Steam and used Express installation for RSS/RO in CKAN as it recommended by RSS/RO manual. Then i've installed Principia and run KSP for test. All works great except one moment: test craft slowly increase Ap and decrease Pe. Unfortunately I do not have screenshot for this. But today with new career start I notice strange visual glitch with planets - they are not in ecliptic plane and all of them have orbit going down with spiral motion. Can you please advice. 
I can provide any log from the game and mods if you need to.

Screenshot of Solar system KSP map - https://imgur.com/a/ToEu9LD

Thanks!

**Comment by eggrobin** [comment]
> All works great except one moment: test craft slowly increase Ap and decrease Pe

Assuming these are reported by stock or MechJeb or something like that, these are osculating elements; they vary along your real orbit, because your orbit is about the real Earth, which is lumpy and not a spherical cow; this is the point of the mod.
If you want to know where you will actually be, look at the apsis markers on the prediction in map view, or, for the longer term, at the Principia orbit analyser.

> But today with new career start I notice strange visual glitch with planets - they are not in ecliptic plane and all of them have orbit going down with spiral motion. Can you please advice.

I would advise reading the [Concepts](https://github.com/mockingbirdnest/Principia/wiki/Concepts) page.
You are looking at the trajectories of the planets in the Earth-Centred, Earth-Fixed reference frame, in which they revolve about the Earth over the course of a day.
This is not a glitch, it is what things look like from the surface: the sky is spinning above you, so that the moon, the sun, and the planets rise and set every day.

I would also advise asking these « getting started » questions on #principia (see the « Getting Help » section of [the FAQ](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions)). There are many people there who will have gone through that learning curve and who will be able to clear up this kind of confusion, whereas here it’s just the two developers.
