### ISSUE TITLE
Flight plan rendering length in target reference frame is limited by current vessel prediction settings, not just plan length

### ISSUE THREAD

**Issue by VeeDeltaVee** [mockingbirdnest/Principia#3471]
While attempting rendezvous in a target reference frame, I encountered an issue where the flight plan would only render a few hours into the future despite setting the plan length to a few days. From @eggrobin on Discord:

> This is limited by the prediction of the target vessel, which, when in the target frame, uses the prediction settings of the current vessel. So the workaround is to increase the prediction steps or tolerance.

This is pretty unintuitive as an end user. Perhaps there should at least be a warning mentioning "Flight plan rendering length limited by current vessel prediction time", at least?

**Comment by pleroy** [comment]
Things look much more intuitive after the change in #3477, but there are two minor inconveniences:
1. The prediction of the target vessel may become very long if the flight plan is, even transiently, made very long.  The computation of the prediction is asynchronous, so it won't affect the game interactivity, but still it does cost something.  The only way to shorten that prediction again is to switch to the target vessel and adjust the number of steps.
2. Only the number of steps of the prediction is increased when the flight plan length is increased, the tolerance is not touched.  This means that manually adjusting the tolerance of the prediction might cause the flight plan to suddenly look shorter.  Its length must be manually increased to compensate for that effect.  This is probably fair because a change of tolerance may cause significant changes to the predictions of the current vessel and the target vessel, and the flight plan may need to be retuned.
