### ISSUE TITLE
Crash when loading a new game

### ISSUE THREAD

**Issue by Yuko-kun** [mockingbirdnest/Principia#3499]
Hello!

The mod looks impressive and great work done! 
Trying to run it in conjunction with the installed mods, but somewhere there is an error and the game crashes without notification.
Created a clean version of KSP and Principia - everything worked and managed to run the ship.
Put the mods back, but removed Kopernicus and Parallax - crashes without notification.
Started to suspect that may be a conflict with mods to edit maneuvers (Precise Maneuver, Trajectories), removed - crashes without notification.

Attached archive with the logs. Very much please help!
[glog.zip](https://github.com/mockingbirdnest/Principia/files/10368072/glog.zip)

**Comment by pleroy** [comment]
Your logs contain:
```
I0108 11:55:22.866273 21800 vessel.cpp:130] Adding part wbiTet (00000000) to vessel UNK-BBV-294 (1fdfe997-06c2-4c83-9751-5afed97cfc82)
```
This part comes from Blueshift, and Blueshift is incompatible with Principia because it does funky physics and wants to set the positions directly.  It also has parts that are nonphysical (`NaN` inertia) and don't comply with the invariants expected by Principia (part ids set to 0).

I realize that we should call this out explicitly in the FAQs so I am adding [this paragraph](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#blueshift-users).

See also #3188 for more details.

**Comment by Yuko-kun** [comment]
О! I didn't even think of it since I haven't had a chance to try it out yet in the game. Thanks, I'll remove it and check it out soon.

P.S I suspect that these problems may arise with other mods containing a similar implementation of the FTL engine...
