### ISSUE TITLE
Principia looking in the PDLauncher directory for principia.dll instead of the KSP directory one folder above it

### ISSUE THREAD

**Issue by Dupiter-AU** [mockingbirdnest/Principia#3523]
OS: Arch Linux, KSP running through Proton 7.0-6

From this error on the main menu principia is looking for principia.dll in the PDLauncher directory rather than the KSP directory above it.
![Screenshot_20230214_140504](https://user-images.githubusercontent.com/82429716/218636593-e7cb0e62-ec2b-413d-88c8-733a4c5d8be7.png)

I've tried two different launch option arguments, but both still lead to the same result
`eval $( echo "gamemoderun mangohud %command%" | sed "s/PDLauncher\/LauncherPatcher.exe'.*/KSP_x64.exe'/" )`
`gamemoderun mangohud "/home/dupiter/.local/share/Steam/steamapps/common/Kerbal Space Program/KSP_64.exe"`

Perhaps a good solution would be to make a check what directory Principia is looking in? E.G. if the folder is called PDLauncher, then go back to the folder above and double check there.

**Comment by pleroy** [comment]
Are you by any chance using a mod that bypasses the Private Division launcher added in 1.12.4?  If so, try without it and tells us if that fixes the issue.

As the FAQ explain "your working directory needs to be \<KSP directory\>, otherwise principia.so will not be found".  It looks like in your case the working directory is `Z:\home\dupiter\.local\share\Steam\steamapps\common\Kerbal Space Program\PDLauncher`, whereas it should be `Z:\home\dupiter\.local\share\Steam\steamapps\common\Kerbal Space Program`.  Note that we are not doing the path lookup ourselves, the Mono native DLL loading mechanisms are.  Tweaking them would not be trivial.
