### ISSUE TITLE
History length slider 

### ISSUE THREAD

**Issue by Krazy0** [mockingbirdnest/Principia#3710]
The max history length slider has a dead zone on the right. Minor issue. 
<img width="440" alt="Principia history slider bug" src="https://github.com/mockingbirdnest/Principia/assets/75238442/e56eb5f5-bc83-471f-9dec-c0d4d868436b">

**Comment by pleroy** [comment]
There is always a "dead zone" but in most sliders it's invisible.  Because the slider is exponential, if you only move it a bit, it would want to increase the history length by a few seconds or even milliseconds.  Because the history length has a granularity of 1 min, this has no effect.

For the other sliders (the ones that control burn) the granularity is much smaller (e.g., 0.001 m/s) so in practice any movement of the slider has an effect.

I am changing the progressivity of the history length slider to reduce the dead zone.  It won't go away entirely, though.
