### ISSUE TITLE
Tidally Locked Bodies Facing Wrong Direction Over Time

### ISSUE THREAD

**Issue by jcyuan06** [mockingbirdnest/Principia#3719]
Due to orbit perturbations, there are slight differences between the orbit period and rotation period for tidally locked bodies. These small differences can accumulate over time, causing a relatively significant error in the orientation the body is facing. Is it possible to correct this type of error by forcing it to face the same direction relative to its parent body?

**Comment by pleroy** [comment]
I don't think that we would want to introduce random hacks in the physics computations to make bodies tidally locked.  As a matter of fact we explicit kill the tidal locking that exists in stock.

Tidal locking doesn't mean that the celestial always maintains the same orientation relative to the primary.  It means that the rotation period (which is effectively constant) matches the orbital period in the long run.  Since the motion along the orbit is not uniform (because of eccentricity and third-body effects), there are small misalignments called [libration](https://en.wikipedia.org/wiki/Libration).

We have been pretty successful with tidal locking for the Trappist system.  The way to do it is to run you system for a long time (tens to hundreds of revolutions of the planet) and set the rotation period to match the (average) revolution period.

This being said, it seems that you are the author of the Kcalbeloh system.  I want to draw your attention to [this comment](https://github.com/mockingbirdnest/Principia/issues/3718#issuecomment-1630354579).  I am convinced that Principia is just not capable of handling such a large system.  Even if you manage to write a working configuration, it is likely that the resulting system will misbehave because of numerical inaccuracies and will be unplayable because of the effect described in that issue.

**Comment by jcyuan06** [comment]
Is there any documentation showing how to get the value of the average revolution period? 
I saw the comment you mentioned before. Currently I'm making a new version to solve this issue. In this version, the size of the entire system is reduced to around 7.2E12m, which is similar to Pluto's SMA. It works pretty well now, the only issue remaining is tidally locked bodies.

**Comment by pleroy** [comment]
> Is there any documentation showing how to get the value of the average revolution period?

Unfortunately there is no easy way; as mentioned on Discord, you'd need a celestial orbit analyser, which doesn't exist at the moment.

A suggestion: you said that you had a good approximation, but you saw a drift.  Run the system until the drift has reached the point where your celestial is again facing in the "right" direction, either because it has done one more rotation than orbital revolutions or one less.  You can use this to deduce with a fairly good accuracy the actual rotation speed.

For instance, if it takes 100 years to reach to point where the celestial has done exactly one rotation less that orbital revolutions, and the duration of an orbital revolution is 1 year, you know that the rotation period is 0.99 years.

**Comment by jcyuan06** [comment]
Thank you! I will try.

**Comment by jcyuan06** [comment]
It works nicely. I added Principia configs in the newest release of my [planet mod](https://github.com/jcyuan06/Kcalbeloh-System).
Thank you for your help!
