### ISSUE TITLE
Changing Integrator Causes Phobos to Escape from the Solar System

### ISSUE THREAD

**Issue by c6ForH66** [mockingbirdnest/Principia#3811]
The default fixed step-size integrator is `QUINLAN_TREMAINE_1990_ORDER_12` But when I tried to change it to `QUINLAN_TREMAINE_1990_ORDER_14` and created a new save, I found that Phobos escaped from Mars and flew to the edge of solar system.

### Steps to Reproduce
- Install a new KSP copy and install RSS, Principia
- Create a new save, Phobos will be orbiting Mars
- Quit game and change the integrator to `QUINLAN_TREMAINE_1990_ORDER_14`
- Launch the game, create a new save, and Phobos will no longer be orbiting Mars, it should be at the edge of the solar system and you would only be able  to focus on it by pressing `Tab` key.

**Comment by pleroy** [comment]
I'm not exactly sure what you expect us to do with this report.  Essentially, the integrator does what it does, and that's not a bug in Principia.

High-order symmetric multistep integrators are susceptible to instabilities, see [Qui99] in the [bibliography](https://github.com/mockingbirdnest/Principia/blob/master/documentation/bibliography.pdf).  In addition, a 14th order integrator is in general operating in the noise of the floating-point rounding errors, which is not a desirable properly from a predictability standpoint.

This is the reason why we picked the 12th order integrator: it is nearly as efficient as the 14th order integrator, but much more stable.  Even so, we did a thorough analysis to make sure that it would correctly predict the solar system as configured in RSS.  I presume that you could do the same and tweak the step size to find a region of stability, but that would be quite a bit of work.

Phobos being very light and heavily perturbed by Mars, it is not unexpected that it would be the first celestial to be affected by instabilities.  That's also what our tests demonstrate, so no surprise here.  I also want to point out that symmetric multistep integrators were originally designed to study the stability of the solar system, i.e., perform integrations on long periods of time, without the satellites of most celestials.  We are using them in a rather different setup, mostly because of their good performance.

**Comment by c6ForH66** [comment]
Thanks for your detailed explanation

**Comment by c6ForH66** [comment]
![image](https://github.com/mockingbirdnest/Principia/assets/41188403/66bd4d6f-7fa6-4f11-9575-d3190302eeb0)

I changed the starting time to 1950 anf found the trajectory of Phobos very funny 😂
