### ISSUE TITLE
Sun-Centered Sun-Fixed reference is SCSF instead of HCHF

### ISSUE THREAD

**Issue by Clayell** [mockingbirdnest/Principia#3887]
SCSF is currently the name of Sun-Centred Sun-Fixed **and** Saturn-Centred Saturn-Fixed. The sun version should be renamed to Heliocentric Fixed to make it consistent with HCI. (Heliocentric Inertial)
![image](https://github.com/mockingbirdnest/Principia/assets/125416952/20ae670f-eacd-4724-9ce2-79174f39b4cc)

**Comment by eggrobin** [comment]
> The sun version should be renamed to Heliocentric Fixed to make it consistent with HCI.

No. We use well-established terms or we apply the default pattern (which is based on well-established terminology), we do not invent new terminology.

**Comment by Clayell** [comment]
> No. We use well-established terms or we apply the default pattern (which is based on well-established terminology), we do not invent new terminology.

Ah, was not aware. Does the overlap between Sun-Centered Sun-Fixed and Saturn-Centered Saturn-Fixed exist in real life too?

**Comment by eggrobin** [comment]
> Does the overlap between Sun-Centered Sun-Fixed and Saturn-Centered Saturn-Fixed exist in real life too?

Cursory googling shows that no, because no-one talks about the Saturn-Centred, Saturn-Fixed reference frame (because no-one cares about the relationship of their trajectory to the surface of Saturn, to the extent that it has one), and very few people talk about the Sun-Centred, Sun-Fixed reference frame. It is easy to find attestations of both Mars-Centred, Mars-Fixed and Moon-Centred, Moon Fixed for example. The abbreviations cannot usefully be unambiguous.
