### ISSUE TITLE
Crash while planning

### ISSUE THREAD

**Issue by kwattt** [mockingbirdnest/Principia#3898]
Crash ocurred while planning a GEO transfer with a vessel target. So far no luck trying to replicate the issue to get a journal. 

[ERROR.20240314-111149.10216.log](https://github.com/mockingbirdnest/Principia/files/14606657/ERROR.20240314-111149.10216.log)
[INFO.20240314-111149.10216.log](https://github.com/mockingbirdnest/Principia/files/14606659/INFO.20240314-111149.10216.log)

**Comment by pleroy** [comment]
Note that there is no Principia crash in these logs (and presumably you don't have a FATAL log file).  If you have [a crash folder](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#have-a-crash-folder), please zip its contents and share it with us.  Otherwise, there is nothing to investigate.

**Comment by kwattt** [comment]
Closing, I don't have a crash folder.
