### ISSUE TITLE
On the lack of 𝐶₂₁ 𝑆₂₁ in the geopotential, and on the maximal degree of gravity models

### ISSUE THREAD

**Issue by ballisticfox** [mockingbirdnest/Principia#4140]
Comparing the given values for the spherical harmonics in `gravity_model.cfg` I believe there might be a value missing, degree 2, order 1.
```
    geopotential_row {
      degree = 2
      geopotential_column {
        order = 0
        cos   = -4.84169457320000017e-04
        sin   = 0.00000000000000000e+00
      }
      geopotential_column {
        order = 2
        cos   = 2.43937341593980011e-06
        sin   = -1.40029401183640008e-06
      }
    }
```

Comparing this with data from: https://earth-info.nga.mil/index.php?dir=wgs84&action=wgs84
it should look similar to
```
    geopotential_row {
      degree = 2
      geopotential_column {
        order = 0
        cos   = -4.84169457320000017e-04
        sin   = 0.00000000000000000e+00
      }
      geopotential_column {
        order = 1
        cos   = -2.06615509074176e-10
        sin   = 1.38441389137979e-09
      }
      geopotential_column {
        order = 2
        cos   = 2.43937341593980011e-06
        sin   = -1.40029401183640008e-06
      }
    }
```

Is there a reason for omitting these values? Additionally EGM08 supports up to degree 2190, is there much of a performance/simulation benefit to higher than order 10?

**Comment by eggrobin** [comment]
> there might be a value missing, degree 2, order 1

This is intentional. The value in question is tiny (it has a smaller norm than any of the coefficients we actually use), so it would not do anything in practice, and since it is present at degree 2, it would result in a performance cost wherever the degree 2 terms are used (most Earth orbits).

This means that we are modeling an Earth which has a slight misalignment between its axis of figure and its rotational pole, but since we don’t model, e.g., the precession of the equinoxes, there are other approximations which dominate this one.

> Additionally EGM08 supports up to degree 2190, is there much of a performance [cost] to higher than order 10?

Yes. The cost is quadratic in the degree (because the order goes up to the degree). 

> is there much of a […] simulation benefit to higher than order 10?

Not on Earth, the Earth is pretty round. On the Moon, this matters, that is why we go up to 30. Back in 2019, we tested up to 50 and compared the behaviour of an interesting lunar orbit from a paper ([RL06] in the [bibliography](https://github.com/mockingbirdnest/Principia/blob/master/documentation/bibliography.pdf)), degree and order 30 was good enough: https://github.com/mockingbirdnest/Principia/blob/8fabf2d8bf80e0c3110f6811126409dec5299b8f/astronomy/lunar_orbit_test.cpp#L254

<img width="1103" alt="rgt orbits" src="https://github.com/user-attachments/assets/07e5424f-d0e4-4e06-a9f8-962836582be4">

See also the long-term trend over 36 cycles of 328 revolutions:
| One point per revolution | One point per cycle (long-term trend) |
|---|---|
| <img width="1373" alt="rgt orbits 36 cycles" src="https://github.com/user-attachments/assets/46bd3f17-165d-4c39-bce3-0c443f060629"> | <img width="1383" alt="rgt orbits 36 cycles trend" src="https://github.com/user-attachments/assets/abaaa1db-62ae-494c-97a8-65934774d143"> |

**Comment by ballisticfox** [comment]
Thanks for the explanation!
