### ISSUE TITLE
Capitalization of hex digits, exponents and literal postfixes

### ISSUE THREAD

**Issue by pleroy** [mockingbirdnest/Principia#847]
Define the convention and fix the code.

**Comment by pleroy** [comment]
* Hexadecimal digits in uppercase, `A-F` with `x` in lowercase.
* Exponent separator in lowercase, `e`.
* Suffixes in lowercase, `ull`.

**Comment by eggrobin** [comment]
There should be no need for `ll` or `l` for integer literals since C++11, see http://en.cppreference.com/w/cpp/language/integer_literal.

* The lowercase rule still applies to other suffixes, `u` for integers, `f` and `l` for floating point.
* In addition, `p` in lowercase in hexadecimal floating-point literals, `b` in lowercase in binary integer literals.
